---
layout: post
title: "Twelve Factor App best practices in microservices with MicroProfile and Kubernetes"
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/10999780?s=400&v=4
seo-title: Twelve Factor App best practices in microservices with MicroProfile and Kubernetes - OpenLiberty.io
seo-description: Twelve Factor App, a widely adopted methodology, defines best practices for creating microservices. MicroProfile and Kubernetes can be used to implement the 12 factors, clarifying the boundary between application and infrastructure, minimising divergence between development and production, and enabling microservices to scale easily.
blog_description:  Twelve Factor App, a widely adopted methodology, defines best practices for creating microservices. MicroProfile and Kubernetes can be used to implement the 12 factors, clarifying the boundary between application and infrastructure, minimising divergence between development and production, and enabling microservices to scale easily.
---

= Twelve Factor App best practices in microservices with MicroProfile and Kubernetes
Emily Jiang <https://github.com/Emily-Jiang>
 
As a microservices developer, you might be wondering whether there are best practices.  Yes, there are: 12 Factor App is a widely adopted methodology for creating microservices. link:https://www.12factor.net[12 Factor App] clarifies the boundary between application and infrastructure, minimises divergence between development and production, and enables your microservices to scale up or down without significant changes to tooling, architecture, or development practices.

The 12 Factor App methodology defines the theory but there is no known implementation. Here is a quick overview of how MicroProfile and Kubernetes can implement the 12 Factors:
 
. Codebase
+
You can use GitHub repositories to provide a dedicated codebase per microservice so that each microservice can have its own release schedule.

. Dependencies
+
Instead of packaging the third-party libraries inside your microservice, specify your dependencies in your Maven `pom.xml` or Gradle `settings.gradle` file. This enables you to freely move up to newer versions.

. Config
+
Configuration is one of the most important factors. The golden rule of developing microservices is to write once, configure everywhere. When changing configuration, you don’t want to repackage your microservices. The way to achieve this is to externalise the configuration from the microservice application code. link:https://www.eclipse.org/community/eclipse_newsletter/2017/september/article3.php[MicroProfile Config] enables you to place configuration in properties files that can be easily updated without recompiling your microservices.
 
. Backing services
+
Treat backing services as attached resources. They should be configurable so that you can easily switch the attached resource by just changing the configuration. Again, MicroProfile Config can help here.

. Build, release, run
+
Separate build, release, and run stages. Seriously.

. Processes
+
Microservices should be stateless. REST is a well adopted transport protocol, and JAX-RS can be used to achieve a RESTful architecture. Systems that follow the REST paradigm are stateless. In this way, underlying infrastructure can destroy or create new microservices without losing any information.

. Port binding
+
Export services using port binding. In the world of microservices, it is common that microservices talk to each other. When deploying them in the cloud, the ports need to change, so it is important to have a way to rebind the port. MicroProfile Config can help this. You can specify the new port in Kubernetes ConfigMap, and MicroProfile Config automatically picks up the value to give the correct info to the deployed microservices. link:https://openliberty.io/blog/2018/01/31/mpRestClient.html[MicroProfile Rest Client] can help with creating client code to connect from one microservice to another.

. Concurrency
+
The microservices should be able to be scaled up or down, depending on the workload. link:https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Kubernetes autoscaler]
 can help with this.

. Disposability
+
Microservices should be robust but gracefully shut down when necessary. Microservices should be fault tolerant and able to function under any situation. link:https://www.eclipse.org/community/eclipse_newsletter/2017/september/article4.php[MicroProfile Fault Tolerance] can help out with this. They should also, however, be treated like cattle, not pets: without identity and be replaceable. If a microservice process is not healthy, underlying cloud infrastructure should be able to directly kill it and quickly start a new one.
 
. Dev/prod parity
+
The best practice of operating on microservices is keeping development, staging, and production environments as similar as possible. Docker images are here to ensure that the environments stay the same so that you don't run into the problem of “it runs on _my_ laptop".

. Logs
+
Treat logs as event streams. You should stream out logs in real time so that killing an instance does not cause logs to go missing.

. Admin processes
+
Do not put one-off admin process inside your microservices; run them as Kubernetes tasks instead. In this way, your microservices can focus on business logic.
 
In summary, use MicroProfile and Kubernetes to help you follow the best practices of the 12 Factor App methodology when creating robust, scalable microservices.

For more detail on this, watch my https://youtu.be/Ov3BbGl2iyQ?t=272[Devoxx UK] talk in which I demonstrate how to create two 12 factor microservices and deploy them to Minikube.
