---
layout: post
title: "12 Factor App Authentication"
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/10999780?s=400&v=4
seo-title: 12 Factor App Authentication - OpenLiberty.io
seo-description: 12 Factor App is widely adopted methodology, and 12 Factor App is to clarify the boundary between application and infrastructure.
blog_description:  12 Factor App is widely adopted methodology, and 12 Factor App is to clarify the boundary between application and infrastructure.
---

= 12 Factor App in Action
Emily Jiang <https://github.com/Emily-Jiang>


If you create microservices, you might be wondering whether there are best practices.  Yes, there is, 12 Factor App is a widely adopted methodology. 12 Factor App is to clarify the boundary between application and infrastructure; minimise divergence between development and production; enable your microservices to scale up or down without significant changes to tooling, architecture or development practices.
The 12 Factor App defines the theory. There is no known implementation. 

In my talk of Building 12-Factor Microservices, I will demonstrate to you how MicroProfile and Kubernetes can implement the 12 Factors. 


Below is a quick overview:

You can use GitHub to achieve the requirement of dedicated codebase per microservice so that the microservices can have their own release schedule.

Codebase
You can use github to achieve the requirement of dedicated codebase per microservice so that the microservices can have their own release schedule.

Dependencies
Do not package the third-party libraries inside your microservice but specifying your dependencies in your maven pom.xml or Gradle dependencies. In this case, you can freely move up to the newer version.


Config
Config is one of the most important factors. The golden rule of developing microservices is that “writing once, configure everywhere”. When changing configuration, you don’t want to repackage your microservices. The way to achieve this is to externalise the configuration from microservices. MicroProfile Config can be used to achieve this. Refer to this blog to learn more on MicroProfile Config.
 
Backing services
Treating backing services as attached resources. They should be configurable so that you can easily switch the attached resource by just changing the configuration. Again, MicroProfile Config can help here.

Build, Release, Run
This is a best practice. Separate build, release and run stages seriously.

Processes
Microservices should be stateless. RESTful is a well adopted transport protocol. JAX-RS can be used to achieve RESTful architecture. Systems that follow the REST paradigm are stateless. In this way, underline infrastructure can destroy or create new microservices without losing any information.


Port Binding
Export services via port binding. In the world of microservices, it is common that microservices talk to each other. When deploying them in the cloud, the ports need change. Therefore, it is important to have a way to rebind the port. MicroProfile Config can help this. You can specify the new port in Kubernetes ConfigMap, and then MicroProfile Config will automatically pick up the value and give the correct info to the deployed microservices. MicroProfile Rest Client can help with the connections of microservices. Check this blog for more info about Rest Client.


Concurrency
The microservices should be able to be scaled up or down, depending on the workload. Kubernetes autoscaler can help with this.

Disposability
Microservices should be treated like cattle, not pets. They should not have identity and replaceable. If a microservice process is not healthy, underline cloud infrastructure should directly kill it and stand up a new one. The other aspect of disposability is to ensure microservices are fault tolerance, and they should be able to function under any situation. MicroProfile Fault Tolerance can help out. Read this blog to know more about MicroProfile Fault Tolerance.
 

Dev/prod parity
The best practice of operating on microservices is keeping development, staging and production as similar as possible. Docker images are here to help so that you will not run into the issue of “It runs on my laptop”.

Logs
Treat logs as event streams. You should stream out logs at real time so that killing an instance will not cause logs missing.


Admin processes
Do not put one-off admin process inside your microservices, but run them as Kubernetes tasks. In this way, your microservices focus on just business logic.
 
 ---
== Conclusion 

In summary, using MicroProfile and Kubernetes will be able to achieve 12 Factor App methodology. In my talk, I will create two microservices and deploy them to minikube and demonstrate the 12 Factors.




