---
layout: post
title: "Develop on cloud nine with Open Liberty"
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/4803104
author_github: https://github.com/yeekangc
seo-title: Enhancements in developer experience - OpenLiberty.io
seo-description: We are delivering various exicting improvements to make Open Liberty even better for cloud-native Java developers.
blog_description: We are delivering various exicting improvements to make Open Liberty even better for cloud-native Java developers.
---
= Develop on cloud nine with Open Liberty
YK Chang <https://github.com/yeekangc>

Liberty is designed for developers from day one.
From fast startup, dynamic update capabilities to a modular architecture that allows you to work with only what you need,
Liberty is meant to delight developers.

We want you to develop your code https://twitter.com/emilyfhjiang/status/1170301544916537345[on cloud nine] with us.
So, we have not rested on what we had and have been busy.
We are now ready to share some of what we have done with you (if you haven't seen them already).

== Liberty Maven Plugin 3.0
We newly released version 3.0 of our https://github.com/OpenLiberty/ci.maven[Maven plugin].
We have simplified a bunch of stuff so you only need add the few lines below in your POM file to pick up the plugin,
launch into our development mode, and you can write code right away.

[source,xml]
----
<plugin>
    <groupId>io.openliberty.tools</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <version>3.0</version>
</plugin>
----

Speaking of our development mode ...

== Dev Mode
It has been talked about https://blog.sebastian-daschner.com/entries/openliberty-plugin-dev-mode[before].
And, with the 3.0 release of our Maven plugin,
https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev[dev mode] is now officially part of the repertoire.

With the plugin configured, run `mvn liberty:dev` from your command line,
open up your favourite editor and get ready to code. We will handle the rest for you.
We will setup and launch the latest version of the runtime, detect changes on the fly and deploy them,
run unit and integration tests right away ... we will do all these and sweat the details for you so you can focus on your code.

Some of these capabilities like dynamic updates are not net new for Liberty and have always been there.
We are putting them together in a development mode to provide you an integrated and delightful experience plus more.

Going beyond Open Liberty ...

== Boost
We introduced https://microprofile.io/2019/04/18/build-your-microprofile-apps-quickly-with-boost/[Boost] a while back.
We did not stop there and have been tinkering away since.

We are releasing a version 0.2 for you to https://github.com/MicroShed/boost/wiki[try].
The idea behind Boost is simplify what you need to do to manage your dependencies and configuration across runtimes,
starting with Eclipse MicroProfile and perhaps eventually Jakarta EE.
We have added dependency support for the different versions of MicroProfile specifications up to 3.0 as well as JPA support too.
Let us know what do you think of Boost.

And, of course, Boost now works with dev mode and MicroShed Testing.

== MicroShed Testing
We all know that testing is important.
Then, many times, it is easier said than done especially with automated integration tests that reflect production environment.
http://microshed.org/microshed-testing/[MicroShed Testing] is meant to address this.
Using containers (with https://www.testcontainers.org/[Testcontainers] library),
we want to make it as easy as possible for you to configure the needed test dependencies (like a database or a remote service)
and write tests that are true-to-production for the microservices that you are developing with MicroProfile, Java EE, or Jakarta EE.

Like Boost, MicroShed Testing is still in the early stage, take a look at the 0.4 release and share your thoughts with us.

As an aside, MicroShed - You saw it above and you saw it in the links. What is it?
It is a new GitHub organization where we are collaborating with the community on developer tools for building Java microservices.
For instance, we worked with the MicroProfile community there to build a
https://marketplace.visualstudio.com/items?itemName=MicroShed.mp-starter-vscode-ext[VS Code extension for MicroProfile Starter].
It is an open community for collaboration. Everybody is welcome. Join us there!

From build, code to test, there you have it.
We will write more about these enhancements in the coming days.
Check them out and let us know what you think, we value your feedback.

Don't wait, come and catch a ride to an open cloud-nine universe with us now!
