---
layout: post
title: "MicroProfile Context Propagation in Open Liberty"
categories: blog
author_picture: https://avatars2.githubusercontent.com/u/13710803
seo-title: MicroProfile Context Propagation in Open Liberty - OpenLiberty.io
seo-description: MicroProfile Context Propagation provides a ManagedExecutor and ThreadContext API that enables you to make better use of completion stages. An implementation of the MicroProfile Context Propagation specification is now available.
blog_description: "MicroProfile Context Propagation provides a ManagedExecutor and ThreadContext API that enables you to make better use of completion stages. An implementation of the MicroProfile Context Propagation specification is now available."
---

= MicroProfile Context Propagation in Open Liberty
Nathan Rauh <https://github.com/njr-11>

CompletionStage and CompletableFuture (first introduced in Java SE 8) enable you to chain together pipelines of dependent actions, where execution of each dependent stage is triggered by the completion of the stage(s) upon which that stage depends. MicroProfile Context Propagation builds upon this model, giving dependent stage actions consistent and reliable thread context and defaulting asynchronous dependent stage actions to run on the Liberty global thread pool. MicroProfile Context Propagation introduces the https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ManagedExecutor.html[ManagedExecutor] and https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ThreadContext.html[ThreadContext] API to accomplish this. An implementation of the MicroProfile Context Propagation specification is now available in https://openliberty.io/downloads[Open Liberty 19.0.0.8].

Managed executors in MicroProfile Context Propagation allow you to use completion stages that run with predictable thread context regardless of which thread the action ends up running on. Without this feature, thread context of a completion stage action depends on whether the action runs on the requesting thread, the thread of a stage upon which it depends, a thread that is requesting the result, or a thread that forcibly completes the prior stage. There is no guarantee under which context the action will run.  However, with MicroProfile Context Propagation, the thread context is completely deterministic because context is always captured from the thread that creates the completion stage and applied when running the action. 

Alternatively, you can configure to clear certain context types rather than capturing context.  For example, clearing the security context means that no user is associated with the thread while the completion stage action runs. When a completion stage is created by a managed executor, the managed executor remains associated with the completion stage and determines thread context propagation for dependent stages that are requested to run asynchronously without designating a specific executor. The managed executor remains associated with each dependent stage created, and each dependent stage created from those, and so forth, allowing for predictable thread context propagation at every stage in the pipeline.

Here is an example of a managed executor that is used to propagate the application's namespace to an asynchronous action,

[source, java]
----
CompletableFuture<Integer> stage = executor.supplyAsync(supplier1)
    .thenApply(function1)
    .thenApply(function2)
    .thenApply(i -> {
        try {
            DataSource ds = InitialContext.doLookup("java:module/env/jdbc/ds1");
            ...
            return result;
        } catch (Exception x) {
           throw new CompletionExeption(x);
        }
    });
----

Managed executors in MicroProfile Context Propagation are fully compatible with https://openliberty.io/docs/ref/javadocs/liberty-javaee8-javadoc/javax/enterprise/concurrent/ManagedExecutorService.html[ManagedExecutorService] in Jakarta/Java EE Concurrency, leaving open the possibility that the programming models could one day be merged.  Notably, the https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ManagedExecutor.html[org.eclipse.microprofile.context.ManagedExecutor] interface inherits from https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ExecutorService.html[java.util.concurrent.ExecutorService], and thus allows the same execute/submit/invoke operations as https://openliberty.io/docs/ref/javadocs/liberty-javaee8-javadoc/javax/enterprise/concurrent/ManagedExecutorService.html[ManagedExecutorService].

MicroProfile Context Propagation provides the https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ThreadContext.html[org.eclipse.microprofile.concurrent.ThreadContext] interface to pre-contextualize completion stage actions. This is useful if you have an umanaged completion stage that is not thread-context aware. When you have a completion stage that isn't created by a managed executor, it can still run with predictable thread context if you pre-contextualize its action with the corresponding method of MicroProfile Context Propagation https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ThreadContext.html[ThreadContext].  For example,

[source, java]
----
CompletableFuture<Long> stage = CompletableFuture.supplyAsync(supplier1)
    .thenApplyAsync(function1)
    .thenApply(threadContext.contextualFunction(function2));
----

In the example above, `supplier1` and `function1` run with non-deterministic thread context. However, the pre-contextualized action, `function2`, always runs with the context of the thread that invoked the `contextualFunction` operation.

== How to obtain ManagedExecutor and ThreadContext instances

There are a variety of ways to obtain instances of `ManagedExecutor` and `ThreadContext`:

* MicroProfile Context Propagation offers a fluent builder pattern for programmatic usage:
+
[source, java]
----
ManagedExecutor executor = ManagedExecutor.builder()
    .maxAsync(10)
    .propagated(ThreadContext.APPLICATION, ThreadContext.SECURITY)
    .cleared(ThreadContext.ALL_REMAINING)
    .build();
----
+
Applications must take care to shut down executor instances that they build, once the executor instance is no longer needed.

* If you are using Java EE Concurrency, you can cast your existing `ManagedExecutorService` to `ManagedExecutor`.

* MicroProfile Context Propagation also lets you configure and inject instances via CDI (requires the `cdi-2.0` feature or higher).
+
Example usage in a CDI bean:
+
[source,java]
----
// CDI qualifier which is used to identify the executor instance
@Qualifier
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER })
public @interface AppContext {}

// Example producer field, defined in a CDI bean,
@Produces @ApplicationScoped @AppContext
ManagedExecutor appContextExecutor = ManagedExecutor.builder()
    .propagated(ThreadContext.APPLICATION)
    .build();

// Example disposer method, also defined in the CDI bean,
void disposeExecutor(@Disposes @AppContext exec) {
    exec.shutdownNow();
}

// Example injection point, defined in a CDI bean,
@Inject @AppContext
ManagedExecutor executor;

...

CompletableFuture<Integer> stage = executor
    .supplyAsync(supplier1)
    .thenApply(function1)
    .thenApplyAsync(value -> {
        try {
            // access resource reference in application's java:comp namespace,
            DataSource ds = InitialContext.doLookup("java:comp/env/jdbc/ds1");
            ...
            return result;
        } catch (Exception x) {
            throw new CompletionException(x);
        }
    });
----

== Propagation of CDI Context

MicroProfile Context Propagation adds the concept of propagating CDI context with finer granularity than application scope. (Propagation of application scope is covered by ThreadContext.APPLICATION, which propagates the identity of the application and its components). With ThreadContext.CDI enabled, dependent stage actions can access any request scoped beans that you have already accessed within the request being propagated, as of the point in time when thread context is captured.

----
@Inject MyRequestScopedBean bean1;
@Inject OtherRequestScopedBean bean2;

@Produces @ApplicationScoped
ManagedExecutor executor = ManagedExecutor.builder().propagated(ThreadContext.CDI).build();
...
bean1.getHeight();
// bean2 is not accessed before this point
stage = executor.supplyAsync(() -> {
    if (useBean1)
        return bean1.getLength(); // bean1 is accessible while request remains active
    else
        return bean2.getWidth(); // causes stage to complete exceptionally
});
----

== Propagation of Transaction Context

MicroProfile Context Propagation adds the ability to propagate JTA transaction context for serial use. This is an advanced capability and should only be used with caution and full awareness of its implications. By default, Open Liberty clears transaction context, which means that any transaction that might have been active on the thread is suspended for the duration of the completion stage action, allowing you to begin and end your own transactions within the implementation of your dependent stage actions.

If you have a scenario where you wish to include multiple completions stage actions within a single transaction, there are a number of considerations that you will need to be aware of. This includes guaranteeing that the transaction is rolled back if any of the stages fail, suspending the transaction from is original thread and enforcing serial usage of the transaction, determining if all of the enlisted resource types support usage across multiple threads, and considering connection pooling/sharing implications that could lead to extra resource consumption.

The following example shows a transaction that is started and later suspended from the main thread with its sole purpose being the capturing of its context. The transaction is suspended via an Open Liberty-specific transaction manager API.  The transactional operations occur at a future point in response to the completion of a triggering action.

----
ManagedExecutor executor = ManagedExecutor.builder()
    .propagated(ThreadContext.TRANSACTION, ThreadContext.APPLICATION)
    .build();
...

// Some example actions that perform simple transactional operations,
Function<Integer, Integer> actionA = numUpdates -> {
    try (Connection con = dataSource.getConnection(); Statement st = con.createStatement()) {
        return numUpdates + st.executeUpdate(sqlA);
    } catch (SQLException x) {
        throw new CompletionException(x);
    }
};

Function<Integer, Integer> actionB = numUpdates -> {
    try (Connection con = dataSource.getConnection(); Statement st = con.createStatement()) {
        return numUpdates + st.executeUpdate(sqlB);
    } catch (SQLException x) {
        throw new CompletionException(x);
    }
};

// This stage must not complete until the transaction is no longer active on the main thread.
CompletableFuture<Integer> initialStage = executor.newIncompleteFuture();

// Arrange for dependent stages to run under the transaction
tx.begin();
try {
    finalStage = initialStage.thenApply(actionA)
                             .thenApply(actionB)
                             .whenComplete((result, failure) -> {
        try {
            if (failure == null && tx.getStatus() == Status.STATUS_ACTIVE)
                tx.commit();
            else
                tx.rollback();
        } catch (Exception x) {
            if (failure == null)
                throw new CompletionException(x);
        }
    });
} finally {
    com.ibm.tx.jta.TransactionManagerFactory.getTransactionManager().suspend();
}

...
// Invoke this from any thread to cause the dependent actions to run under the transaction:
initialStage.complete(0);

...
// Once the executor is no longer needed:
executor.shutdown();
----

== Conclusion

MicroProfile Context Propagation builds upon Java SE CompletableFuture and builds out the necessary infrastructure around it, empowering you to build robust applications that react to events as they happen, under a dependable thread context and backed by the performance of Liberty threading.