---
layout: post
title: "Develop on cloud nine with Open Liberty"
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/4803104
author_github: https://github.com/yeekangc
seo-title: Enhancements in developer experience - OpenLiberty.io
seo-description: We recently delivered various improvements to make Open Liberty even better for cloud-native Java developers - Simplified Maven plugin, development mode that minimised turnaround time, and framework for easy integration tests.
blog_description: We recently delivered various improvements to make Open Liberty even better for cloud-native Java developers - Simplified Maven plugin, development mode that minimised turnaround time, and framework for easy integration tests.
---
= Develop on cloud nine with Open Liberty
YK Chang <https://github.com/yeekangc>

We designed Liberty for developers from the start.
We recently delivered enhancements to make Open Liberty even better for developers.
We simplified our Maven plugin so you can simply pick up and go,
we are introducing a development mode that detect and deploy changes on the fly while you are coding,
and we are collaborating on an integration test framework so you can write automated true-to-production tests easily.

== Easy-to-use Maven plugin
We newly released version https://github.com/OpenLiberty/ci.maven/releases/tag/liberty-maven-3.1[3.1] of our https://github.com/OpenLiberty/ci.maven[Maven plugin].
Starting with the 3.0 release, we simplified https://github.com/OpenLiberty/ci.maven/releases/tag/liberty-maven-3.0[a bunch of stuff] so you only need add the few lines below in your POM file to pick up the plugin,
launch into our development mode, and you can write code immediately.

[source,xml]
----
<plugin>
    <groupId>io.openliberty.tools</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <version>3.1</version>
</plugin>
----

Speaking of our development mode ...

== Optimised development with dev mode
It has been talked about https://blog.sebastian-daschner.com/entries/openliberty-plugin-dev-mode[before].
Now, with the 3.0 release of our Maven plugin,
https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#dev[dev mode] is now officially part of the repertoire.

With the plugin configured, run `mvn liberty:dev` from your command line,
open up your favourite editor and get ready to code. We will handle the rest for you.
We will setup and launch the latest version of the runtime, detect changes on the fly and deploy them,
run unit and integration tests on demand or right away ... we will do all these and sweat the details for you so you can focus on your code.

Some of these capabilities like dynamic updates are not net new for Liberty and have always been there.
We are putting them together in a development mode to provide you an integrated (and delightful) experience plus more.

O yes, we have also built a
https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[VS Code extension for dev mode] too.

Going beyond Open Liberty ...

== Easy and true-to-production integration tests with MicroShed Testing
We all know that testing is important.
Then, many times, it is easier said than done especially with automated integration tests that reflect the production environment.
https://microshed.org/microshed-testing/[MicroShed Testing] is meant to address this.
Using containers (with https://www.testcontainers.org/[Testcontainers] library),
we want to make it as easy as possible for you to configure the needed test dependencies (like a database or a remote service)
and write tests that are true-to-production for the microservices that you are developing with MicroProfile, Java EE, or Jakarta EE.

MicroShed Testing is still in the early stage, take a look at the https://github.com/MicroShed/microshed-testing[0.4] release and share your thoughts with us.

As an aside, MicroShed - You saw it above and you saw it in the links. What is it?
It is a new GitHub organization where we are collaborating with the community on developer tools for building Java microservices.
For instance, we worked with the MicroProfile community there to build a
https://marketplace.visualstudio.com/items?itemName=MicroShed.mp-starter-vscode-ext[VS Code extension for MicroProfile Starter].
It is an open community for collaboration. Everybody is welcome so join us there!

From build, code to test, there you have it.
We will write more about these enhancements in the coming days.
Check them out and let us know what you think, we value your feedback.

Tap us on Gitter or file issues and send us pull requests on GitHub:
* Liberty Maven plugin and dev mode: https://gitter.im/OpenLiberty/developer-experience[Gitter] https://github.com/OpenLiberty/ci.maven[GitHub]
* MicroShed Testing: https://gitter.im/MicroShed/microshed-testing[Gitter] https://github.com/MicroShed/microshed-testing[GitHub]

++++
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Fresh from printing! My favorite t-shirt, originated from my vision for <a href="https://twitter.com/hashtag/CloudNative?src=hash&amp;ref_src=twsrc%5Etfw">#CloudNative</a> : <a href="https://twitter.com/MicroProfileIO?ref_src=twsrc%5Etfw">@MicroProfileIO</a> <a href="https://twitter.com/JakartaEE?ref_src=twsrc%5Etfw">@JakartaEE</a> in <a href="https://twitter.com/OpenLibertyIO?ref_src=twsrc%5Etfw">@OpenLibertyIO</a> , which takes you to the <a href="https://twitter.com/hashtag/Cloud?src=hash&amp;ref_src=twsrc%5Etfw">#Cloud</a> 9 😀 <a href="https://t.co/09HheTYEJK">pic.twitter.com/09HheTYEJK</a></p>&mdash; Emily Jiang (@emilyfhjiang) <a href="https://twitter.com/emilyfhjiang/status/1170301544916537345?ref_src=twsrc%5Etfw">September 7, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

Don't wait, come and catch a ride to an open cloud-nine universe with us now!
