---
layout: post
title: "A better way to use MongoDB with OpenLiberty"
date:   2019-01-22 11:30:00 -0000
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/21284019
seo-title: A better way to use MongoDB with OpenLiberty - OpenLiberty.io
seo-description: Use a MongoProducer to make accessing MongoDB easy, with CDI and MicroProfile Config.
blog_description: "Use a MongoProducer to make accessing MongoDB easy, with CDI and MicroProfile Config."
---

= A better way to use MongoDB with OpenLiberty
Mark Swatosh <https://github.com/mswatosh>

== The MongoProducer
Using MongoDB with OpenLiberty previously meant enabling a mongo feature and configuring in server.xml, but was limited to certain versions of MongoDB.
 Now, with improvements in CDI and the introduction of MicroProfile Config, you can easily configure access to any version of MongoDB, by creating a MongoProducer. 
A MongoProducer is a class that allows you to inject a MongoDatabase (using CDI's `@Produces`) into your application. An example of a MongoProducer is below:

[source, java]
----
import java.util.Collections;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Disposes;
import javax.enterprise.inject.Produces;
import javax.inject.Inject;
import javax.net.ssl.SSLContext;

import org.eclipse.microprofile.config.inject.ConfigProperty;

import com.ibm.websphere.crypto.PasswordUtil;
import com.ibm.websphere.ssl.JSSEHelper;
import com.ibm.websphere.ssl.SSLException;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientOptions;
import com.mongodb.MongoCredential;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoDatabase;

@ApplicationScoped
public class MongoProducer {

    @Inject
    @ConfigProperty(name = "mongo.hostname", defaultValue = "localhost")
    String hostname;

    @Inject
    @ConfigProperty(name = "mongo.port", defaultValue = "27017")
    int port;
	
    @Inject
    @ConfigProperty(name = "mongo.dbname", defaultValue = "testdb")
    String dbName;
	
    @Inject
    @ConfigProperty(name = "mongo.user")
    String user;
	
    @Inject
    @ConfigProperty(name = "mongo.pass.encoded")
    String encodedPass;
	
    @Produces
    public MongoClient createMongo() throws SSLException {
        String password = PasswordUtil.passwordDecode(encodedPass);
        MongoCredential creds = MongoCredential.createCredential(user, dbName, password.toCharArray());
        SSLContext sslContext = JSSEHelper.getInstance().getSSLContext("mySSL", Collections.emptyMap(), null);
        return new MongoClient(new ServerAddress(hostname, port), creds, new MongoClientOptions.Builder()
                              .sslEnabled(true)
                              .sslContext(sslContext)
                              .build());
    }

    @Produces
    public MongoDatabase createDB(MongoClient client) {
        return client.getDatabase(dbName);
    }

    public void close(@Disposes MongoClient toClose) {
        toClose.close();
    }
}
----


MongoProducers can come in different forms, and be taylored to your needs. 
The full example above shows MongoDB being used with an encoded password and with SSL configured. For a simpler scenario, the createMongo() method could be reduced to the following:

[source, java]
----
    @Produces
    public MongoClient createMongo() {
        return new MongoClient(new ServerAddress(hostname, port), new MongoClientOptions.Builder().build());
    }
----

=== Configure with MPConfig
Using link:https://openliberty.io/guides/microprofile-config-intro.html[MicroProfile Config] makes configuring the MongoDB Driver simple.
For example, by placing the following in your microprofile-config.properties or server.env file, the values for
user and encodedPass will be pulled into the MongoProducer.

=== No need for a mongo feature
Previously, using MongoDB required enabling the mongo-2.0 feature, which was limited to certain
MongoDB 2.X versions. By using a MongoProducer, any version of MongoDB can be used, with no need for a mongo feature. 
Even if the MongoDB Java Driver API changes, simple updates to the MongoProducer will allow it to continue to work.
You should remove the mongo-2.0 feature from your server.xml when using newer versions of MongoDB with a MongoProducer.

[source, text]
----
mongo.user="mark"
mongo.pass.encoded="{aes}APtt+/vYxxPa0jE1rhmZue9wBm3JGqFK3JR4oJdSDGWM1wLr1ckvqkqKjSB2Voty8g=="
----

== An example with JAX-RS

Here is an example of using the MongoProducer, demonstrating how easy it is to inject and use a 
MongoDatabase in a JAX-RS application.

[source, java]
----
@Inject
MongoDatabase db;

@POST
@Path("/add") 
@Consumes(MediaType.APPLICATION_JSON)
public void add(CrewMember crewMember) {
	MongoCollection<Document> crew = db.getCollection("Crew");
	Document newCrewMember = new Document();
	newCrewMember.put("Name",crewMember.getName());
	newCrewMember.put("Rank",crewMember.getRank());
	newCrewMember.put("CrewID",crewMember.getCrewID());
	crew.insertOne(newCrewMember);
}
----

Hopefully this illustrates just how easy it is to create a MongoProducer, configure it with MicroProfile Config, 
and use it to access a MongoDatabase in your application.