---
layout: post
title: Java 11 and new four-weekly release schedule in Open Liberty 19.0.0.1
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/3322532
seo-title: Java 11 and new four-weekly release schedule in Open Liberty 19.0.0.1 - OpenLiberty.io.
seo-description: Open Liberty 19.0.0.1 works with Java 11! It also provides support for HTTP Forwarded and X-Forwarded-* headers.
blog_description: "Open Liberty 19.0.0.1 works with Java 11! It also provides support for HTTP Forwarded and X-Forwarded-* headers."
---
= Java 11 and new four-weekly release schedule in Open Liberty 19.0.0.1
Laura Cowen <https://github.com/lauracowen>

Happy new year! I know it's February but it's also the first Open Liberty release of 2019. Open Liberty 19.0.0.1 works with Java 11 (ta-dah!), and provides support for HTTP Forwarded and X-Forwarded-* headers. Open Liberty 19.0.0.1 also marks the first release in our new four-weekly release schedule, so you'll be seeing us a lot more often...

== Java 11
Yes, we did it! Open Liberty 19.0.0.1 works with Java 11. We tested it and everything. Several times. Just to be sure. And we're good. Java 11 is the first long-term support major release since Java 8, so it's a bit of a Big Deal. Take a look at URL[Andy Guibert's blog post] in which he talks about the other benefits of using Java 11, how to get your Open Liberty apps running on Java 11, and any caveats that might affect you.

== HTTP Forwarded and X-Forwarded-* headers
URL[Eduardo Breijo blogged about the new headers support] back in December when they appeared in the Open Liberty development builds. This support means that programmers and applications can obtain the original client endpoint information presented by a proxy or a load balancer using the Forwarded or X-Forwarded-* headers instead of the current TCP connected endpoint. This information can be retrieved using certain Servlet API calls or the NCSA Access Log. Eduardo explains more in his blog post and describes how to use it.


== Four-weekly release schedule

In 2019, we have more frequent releases coming at you, starting with Open Liberty 19.0.0.1.. This is a significant change from our previous three-monthly release schedule. The main benefit of this change is that, as a developer, you can now more easily get upstream security fixes in your Open Liberty build through Maven or Docker Hub. Of course, if you don't want to work on the latest release all the time, you don't have to. URL[Alasdair Nottingham explains more in his blog post].

