---
layout: post
title: "Where to get support for Open Liberty"
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/1906689
author_github: https://github.com/nottycode
seo-title: Where to get support for Open Liberty - OpenLiberty.io
seo-description: Open Liberty support is now available from IBM and Red Hat.
blog_description: "Open Liberty support is now available from IBM and Red Hat."
---
= Where to get support for Open Liberty
Alasdair Nottingham <https://github.com/nottycode>

Open Source software runs the world.
No matter what software or hardware you use there is open source involved somewhere.
While there are lots of benefits to open source, when it comes to running business critical operations companies often want the confidence of having experts in the open source software on call in case of problems.
This is commonly achieved by buying a support contract for the software from someone with the expertise in the project and community.
For Open Liberty that support has always been available from IBM, and as of this week it is also available from Red Hat.

If you are interested in support you probably are asking “what does this mean, what are my options and how should I choose”.
A support contract isn’t a requirement, but it does help to fund the development of Open Liberty and it also provides support in the event of the unexpected happening.
What you should go with depends on how you intend to run Open Liberty in production as well as what business relationships you already have.

If you are running outside of containers then you can get support through either the downstream WebSphere Liberty product which is available from IBM as a part of https://www.ibm.com/cloud/websphere-application-server[WebSphere Application Server], or via https://www.ibm.com/ca-en/marketplace/elite-support-for-open-liberty[IBM Elite Support for Open Liberty].
Both of these provide support irrespective of your planned deployment technology.

If you plan to run Open Liberty in a container on Red Hat OpenShift Container Platform you have two additional choices.
If you bought Red Hat OpenShift Container Platform from Red Hat you can also buy https://access.redhat.com/products/open-liberty[Red Hat Runtimes] which provides support for running Open Liberty.
If you get Red Hat OpenShift Container Platform from IBM through https://www.ibm.com/cloud/cloud-pak-for-applications[IBM Cloud Pak for Applications] then you are already entitled to support for Open Liberty.

To summarise support for Open Liberty is now available from Red Hat through Red Hat Runtimes; or IBM through IBM Cloud Pak for Applications, IBM Elite Support for Open Liberty or WebSphere Application Server.
For all of these options the same team are providing the support, it just depends on how you plan to deploy and who is the most convenient company to buy the support from.

To get started with Open Liberty on OpenShift take a look at https://openliberty.io/guides/cloud-openshift.html[the guide].
