---
layout: post
title: "Production experiance with OpenLiberty"
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/43585153?s=400&v=4
seo-title: One-year experience in developing productive applications with OpenLiberty 
seo-description: We are a scrum team of five people working for an independent insurance company under public law and have set ourselves the goal to migrate older applications from a JEE 1.6 compliant platform to OpenLiberty under OpenShift within one year, to use MicroProfiles to their maximum and to make them productive.
blog_description:  We are a scru team of five people working for an independent insurance company under public law and have set ourselves the goal to migrate older applications from a JEE 1.6 compliant platform to OpenLiberty under OpenShift within one year, to use MicroProfiles to their maximum and to make them productive.
---
= One-year experience in developing productive applications with OpenLiberty
Igor Berchtold <www.linkedin.com/in/igor-berchtold-712a76116>

== Our journey starts 
A year ago the project was released to migrate our aging applications from a central JEE platform to a new OpenShift platform. The goals were to promote the autonomy of the development team, to isolate the applications from each other and to improve the development process as a whole.
 
We have checked several Microprofile certified Appservers and soon got the certainty that OpenLiberty has not only an active and well structured community, a production ready product but also supports our desire for agile work according to SAFe with monthly release cycles.

Our plan was to migrate four existing applications using appropriate tools to efficiently develop and meet the requirements for productive use. However, we could not start on a greenfield site but had to consider and integrate into the existing landscape.

Our principles during this journey are based on design first using OpenAPI v3, reuse as much as possible of existing frameworks and platforms as long as it makes sense in a microservice world, conform and use whenever possible standards, best practices and a strait forward implementation strategy without compromising well known enterprise architectural rules (e.g. https://www.opengroup.org/togaf[TOGAF]). 

=== Providing WebServices
Our first application migration was a service to check if an employee was still employed by us to allow him to buy train ticket in the name of our company. This application provides two WebServices according to the interface description of our external partner. To get support for WebServices is very easy using OpenLiberty, just configure additionally the `jaxws-2.2` feature within the `server.xml`. The implementation of the WebServices in turn uses microservices of another application that provides organizational and employee data. 

=== Using Eclipselink/JPA
This second application was redesigned instead of a migration. The data storage is in a MSSQL database, Eclipselink/JPA was used for access. The REST interfaces were designed with OpenAPI v3 and with an OpenAPI generator the corresponding Java objects of the interface were generated. OpenLiberty provides these functionality using `jpa-2.2`, `ejblite-3.2` and `mpOpenAPI-1.1` features. With using this last feature OpenLiberty provides a handy SwaggerUI for developers exploring the microservice functionality. Logging (log4j2) and ExceptionHandling could be reused by the existing framework.

=== Integration into an existing landscape 
The third application provides currency rates for other applications. The use of WebServcies for access to our SAP systems and the currency service supplier was a special feature of this application. This time we did not provide WebServices but we reused existing WebServices. The data is retrieved in batch mode during the night and made available to the other applications. Our company central Batch Scheduler called a microservice using a `curl` command, which then received a ZIP file containing all the necessary files for further distribution. This last step was already part of the old solution and did not have to be adapted. Finally because of some security requirements we used `mpJwt-1.1`, `jwt-1.0` along with `appSecurity-3.0` to get some authentication and authorization functionality out of the box.  

=== All about files
Microservices were created as the fourth application to check PDF files for PDF-A2B conformity, to convert any formats such as Office documents, emails, images to PDF-A2B and to assemble several PDF files into one PDF file. JMS queues were used to meet the high speed and throughput requirements, allowing parallel execution of incoming requests, this functionality was provided by using `jms-2.0`, `wasJmsClient-2.0`, `wasJmsServer-1.0` and `mdb-3.2` features. The interface was also designed with OpenAPI v3. This time we used multipart/form-data for the documents transfer. We have reached the limits of the used JAX-RS standards. Since the use of multipart/form-data is not yet standardized, the necessary Java objects cannot simply be generated with the OpenAPI Generator and used by OpenLiberty. The JAX-RS community is working on extending the standard to https://github.com/eclipse-ee4j/jaxrs-api/issues/418[support multipart/form-data]. Once this will be done the OpenAPI generator can be adapted accordingly and hopefully there would be a possibility to use a standardized interface. Today the IMultipartBody interface must be used in OpenLiberty. 

== Overall experience so far
During our implementation and testing efforts we noticed the out dated version of OpenAPI UI (aka Swagger UI) provided by OpenLiberty. There are newer versions to support the use of multipart/form-data and the upload of files. This would allow us to give the developers a tool to the respective microservices to get familiar with the interface using the "Try it out" feature. Reporting this as an https://github.com/OpenLiberty/open-liberty/issues/9203[issue] to the community we got attention and this should be fixed soon. 

In addition to the actual migration of the applications, we have built a CI/CD pipeline that allows us to deploy our microservices to an existing OpenShift Container Platform easily and efficiently. Each application consists of an OpenLiberty server in a docker container. Depending on scalability and reliability considerations, one or more pods are started at runtime. The time needed to start a pod in our environment depends how many core of cpu are defined to a pod. At the moment we manage to start a pod within 15 seconds, quick enough for our use cases. This is thanks to the low memory footprint of OpenLiberty. 

With the use of MPHealth, MPMetrics we get tools that enable us as a team to take over the operational responsibility. Our experience so far shows that OpenLiberty is very stable and easy to use as long as you have JEE experiance. Our applications run for weeks without restarts, previously we had to restart our central JEE platform weekly.

With our decision to use OpenLiberty we did very well. I am confident that we can achieve our goal of migrating the remaining applications we are responsible for within the coming year.