---
layout: post
title: "The OpenAPI Generator has added support for Eclipse MicroProfile"
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/28316667
author_github: https://github.com/turkeylurkey
seo-title: OpenAPI Generator has added support for Eclipse MicroProfile - OpenLiberty.io
seo-description: Develop microservices quicker using the OpenAPI Generator and the Eclipse MicroProfile programming framework.
blog_description: "Develop microservices quicker using the OpenAPI Generator and the Eclipse MicroProfile programming framework."
---
= The OpenAPI Generator has added support for Eclipse MicroProfile
Paul Gooderham <https://github.com/turkeylurkey>

If your application calls a lot of microservices you'll want all the help you can get. And if you use Eclipse MicroProfile you can now use the OpenAPI Generator to get that help.

The client generator works for remote RESTful microservices that are described using the OpenAPI specification. The service's endpoints and data types are described in yaml or JSON format and should be available as a file or for download from a URL.

== Command Line

There are two ways to get started. The first is to download the official build and invoke the generator from the command line. See https://github.com/OpenAPITools/openapi-generator#13---download-jar[1.3 - Download JAR] and look for the jar location, e.g.: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/4.2.3/openapi-generator-cli-4.2.3.jar

After you download the jar you can use a command similar to the following. Specify a yaml file that describes the remote service, the package names you'd like to appear in your new Java files and the directory where the output should appear.
-----
java -jar openapi-generator-cli-4.2.3.jar \
  generate    \
  --generator-name java \
  --library microprofile \
  --input-spec petstore.yaml \
  --api-package org.acme.ourapp.petstore.api \
  --model-package org.acme.ourapp.petstore.model \
  --output output_dir/client/petstore
-----
This command will generate Java objects that represent the data the microservice recognises and Java interface files that describe methods which represent the REST endpoints. You complete the work by coding the implementations.

== Visual Studio Code

Alternatively, if you are writing your code using Visual Studio Code you can download the client generator as an extension. See the marketplace page for download and install instructions. https://marketplace.visualstudio.com/items?itemName=MicroProfile-Community.mp-rest-client-generator-vscode-ext[Visual Studio Code Marketplace].

After installing the extension just right click the directory where the ouput files should be placed and select Generate a MicroProfile Rest Client. Navigate to the yaml file, confirm the directory and package names and hit enter. The generator will run and provide the Java model objects and API interfaces described previously.
