---
layout: post
title: "MicroProfile and Open Liberty at DevNexus 2019 in Atlanta"
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/21284019
seo-title: MicroProfile and Open Liberty at DevNexus 2019 in Atlanta - OpenLiberty.io
seo-description: 
blog_description: ""
---
= MicroProfile and Open Liberty at DevNexus 2019 in Atlanta
Laura Cowen <http://github.com/lauracowen>

Several of the Open Liberty team will be at https://devnexus.com/[DevNexus 2019] in Atlanta on 6-8 March. Deciding which of the great talks to see at DevNexus looks like it'll be a challenge, so here's a quick summary of the sessions on Open Liberty or MicroProfile.

== Workshops at DevNexus 2019

https://devnexus.com/presentations/3170/[Hands-on cloud-native Java with MicroProfile, Kubernetes and Istio]
https://twitter.com/gcharters[Graham Charters] and https://twitter.com/emilyfhjiang[Emily Jiang] will lead this workshop on what it means to be cloud-native and how that impacts application development. They'll introduce you to https://microprofile.io/[Eclipse MicroProfile] and help you to either get started with the basics of REST services or to jump right in and develop secure, fault tolerant, configurable, and monitorable microservices. They'll then show you how to package and deploy your app in Docker containers in a Kubernetes cluster.

https://devnexus.com/presentations/3560/[Java application security the hard way]
OpenJ9's https://twitter.com/spoole167[Steve Poole] will team up with Snyk Director of Developer Relations https://twitter.com/sjmaple[Simon Maple] to lead this fun session on how to build your "security memory muscle" and help you learn how to make your Java apps more secure.

== Talks at DevNexus 2019

https://devnexus.com/presentations/3165/[Are you ready for cloud-native Java?]
OpenJ9's https://twitter.com/spoole167[Steve Poole] and Open Liberty's https://twitter.com/gcharters[Graham Charters] will talk you through the concept of developing cloud-native Java applications. Find out more about what cloud-native Java looks like and how it can differ from expectations. Steve and Graham will point out what to be aware of and which open technologies can help you.

https://devnexus.com/presentations/3296/[MicroProfile and Jakarta EE - What's Next?]
MicroProfile and Open Liberty's https://twitter.com/kwsutter[Kevin Sutter] will look into the future of the MicroProfile and Jakarta EE projects, answering common questions such as "What's next for each project?" and "Will MicroProfile and Jakartaa EE merge or stay separate?". If you want to know the answers, this is where you'll get Kevin's latest view on it all.


https://devnexus.com/presentations/2976/[Bulletproof Java Enterprise Applications for The Hard Production Life]
https://twitter.com/DaschnerS[Sebastian Daschner] discusses the harsh realities of production to Java Enterprise applications and how to meet production requirements in your apps.

https://devnexus.com/presentations/2975/[Zero-downtime Java Enterprise Applications With Kubernetes]
https://twitter.com/DaschnerS[Sebastian Daschner] talks through what to do to achieve zero-downtime with Kubernetes with your production Java Enterprise applications.


And, finally, a couple of talks about MicroProfile by others contributing to the the MicroProfile project:


https://devnexus.com/presentations/3278/[MicroProfile Survival Guide in the Cloud]
Edson Yananga (Red Hat) and Bruno Borges (Microsoft)

https://devnexus.com/presentations/3306/[Stateless Microservice Security via JWT and MicroProfile]
David Blevins (Tomitribe)


You can find the https://devnexus.com/schedule[full schedule] on the https://devnexus.com[conference website].