---
layout: post
title: "Updates to JAAS Custom Login Modules are now available on Open Liberty 20.0.0.5"
categories: blog
author_picture: https://avatars3.githubusercontent.com/tomjenningss
author_github: https://github.com/tomjenningss
seo-title: Open Liberty 20.0.0.5 provides enhanced, updated features to JAAS Custom Login Modules which means you can now use JAAS Custom Login Modules that are packaged within resource adapters on Open Liberty 20.0.0.5
seo-description: Open Liberty 20.0.0.5 provides enhanced, updated features to JAAS Custom Login Modules which means you can now use JAAS Custom Login Modules that are packaged within resource adapters
blog_description: Open Liberty 20.0.0.5 provides enhanced, updated features to JAAS Custom Login Modules which means you can now use JAAS Custom Login Modules that are packaged within resource adapters.
---
= Updates to JAAS Custom Login Modules are now available on Open Liberty 20.0.0.5
Tom Jennings <https://github.com/tomjenningss>
:imagesdir: /
:url-prefix:
:url-about: /about/

// tag::intro[]
Open Liberty 20.0.0.5 provides enhanced, updated features to JAAS Custom Login Modules which means you can now use JAAS Custom Login Modules that are packaged within resource adapters..

In link:{url-about}[Open Liberty] 20.0.0.5:

* <<CLM, JAAS Custom Login Modules>>
* <<OLL, Open Liberty Logging>>
* <<JLO, Omit specified fields from JSON logging output>>
* <<EPT, EJB Persistent Timers>>

View the list of fixed bugs in https://github.com/OpenLiberty/open-liberty/issues?q=label%3Arelease%3A20004+label%3A%22release+bug%22+[20.0.0.5].
// end::intro[]

If you're interested in what's coming soon in Open Liberty, take a look at our <<previews,current development builds>> which includes GraphQL with Open Liberty.

// tag::run[]
[#run]

== Run your apps using 20.0.0.5

If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty</groupId>
    <artifactId>openliberty-runtime</artifactId>
    <version>20.0.0.5</version>
    <type>zip</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty', name: 'openliberty-runtime', version: '[20.0.0.5,)'
}
----

Or if you're using Docker:

[source]
----
FROM open-liberty
----
//end::run[]

Or take a look at our link:{url-prefix}/downloads/[Downloads page].

[link=https://stackoverflow.com/tags/open-liberty]
image::img/blog/blog_btn_stack.svg[Ask a question on Stack Overflow, align="center"]

//tag::features[]

[#CLM]
== Updated JAAS Custom Login Modules

Prior to this feature, it was necessary to package (or repackage) JAAS Custom Login Modules into a separate shared library in order to configure Liberty to use them. It is now possible for JAAS Custom Login Modules to remain packaged within a resource adapter. Alternatively, even if you are not using a resource adapter at all, it is now possible to package JAAS Custom Login Modules within your application.

Enable the AppSecurity and JCA features and configure a resource adapter. Use the `classProviderRef` attribute on the `jaasLoginModule` element to reference the `id` of the resource adapter.


[source, xml]
----
<server>
  <featureManager>
    <feature>appSecurity-2.0</feature>
    <feature>jca-1.7</feature>
    ... other features
  </featureManager>

  <resourceAdapter id="eciResourceAdapter" location="${shared.resource.dir}/cicseci.rar"/>

  <!-- classProviderRef indicates that the login module class is found in the resource adapter -->
  <jaasLoginModule id="identityProp" controlFlag="REQUIRED"
      className="com.ibm.ctg.security.idprop.LoginModule"
      classProviderRef="eciResourceAdapter">
    <options propIdentity="Caller"/>
  </jaasLoginModule>

  <jaasLoginContextEntry id="CTGEntry" loginModuleRef="identityProp" name="CTGEntry"/>

  <connectionFactory id="cf1" jndiName="eis/cf1" jaasLoginContextEntryRef="CTGEntry">
    <properties.eciResourceAdapter ConnectionUrl="tcp://localhost" portNumber="2006" serverName="MYSERVER"/>
  </connectionFactory>

  ...
</server>
----

The same approach can be used for JAAS Custom Login Modules that are packaged within an application. Set the `classProviderRef` to point to the `id` of the `application`, `webApplication`, or `enterpriseApplication` element that contains the login module class. When packaging JAAS Custom Login Modules within an application, include the login module within one of the following places:

** Within a top level JAR of the enterprise application.
** Within a resource adapter module of the enterprise application.
** Within the web module of the enterprise application.
** Within an EJB module of the enterprise application.
** Within a web application.

It should be noted that JAAS Custom Login Modules require the use of a resource reference with container managed authentication.

You can find out more about [Configuring a JAAS custom login module for Liberty](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_jaas.html)

[#OLL]
=== Open Liberty logging now has a date and time stamp 

In Liberty, users have the option to format their server logs that appear in the console.log file in different formats, such as JSON and dev (default) formats, in their server logging configuration, using the consoleFormat logging attribute. The dev format will show messages in a basic format, where there are no timestamp or any other relevant information. It will only show the message with its log level and the message itself.

For example:
[source, xml]
----
consoleFormat=dev (default)
[AUDIT ] CWWKE0001I: The server server1 has been launched.
----

This feature introduces a new option called `simple` for the consoleFormat logging server configuration attribute. This new option will configure Liberty to output logs in the same simple (default) format as the message.log file, with date/time stamps and other relevant information, to the `console.log` file or to the console (Standard-out).

For example:

[source, xml]
----
consoleFormat=simple
[25/11/19 10:02:30:080 EST] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager A CWWKE0001I: The server server1 has been launched.
----

To configure the Liberty logs to output logs in the new simple console format, you just have to set the following logging server configuration, in the bootstrap.properties, server.xml, or in the server.env (environment variables).

==== bootstrap.properties
`com.ibm.ws.logging.console.format=simple`

==== server.xml
`<logging consoleFormat="simple"/>`

==== server.env
`WLP_LOGGING_CONSOLE_FORMAT=simple`


[#JLO]
=== Omit specified fields from JSON logging output

In Liberty, users have the option to format their server logs in basic or JSON format. When logs are in JSON format, users have to specify the sources (message, trace, accessLog, ffdc, audit) they want to send to messages.log or console.log/standard-out.

Previously, Liberty has always had the default fields in the JSON output. Users can now specify the JSON fields they want to omit. This feature adds an option for users to omit JSON fields in the JSON logging process. The option to omit JSON field names in Liberty is extremely useful, as users may not want certain default fields provided by Liberty in their JSON output. Undesired fields add to the size of the records which wastes network I/O during record transmissions and waste space in downstream log aggregation tools. Now users have the option to only emit the fields they need so they can send to downstream log aggregation tools without using more space and I/O than necessary.
For someone running liberty in docker containers, with a single server in each container, they may not want to include the JSON fields that represent the server name and user directory, for example.

When logs are in JSON format, you can use the existing `jsonFieldMappings` attribute to omit fields. The attribute initially was only used for renaming field names. For renaming JSON field name, the format is specified as `source:defaultFieldName:newFieldName` or `defaultFieldName:newFieldName`. To omit `defaultFieldName`, leave `newFieldName` empty. For example, to omit a field for all sources, use the following format: `defaultFieldName:` . To omit a field for a specific source, use the following format: `source:defaultFieldName:` where source is the source you want to specify (such as message, trace, accessLog, ffdc, audit).

An example of omitting JSON fields by adding the following to bootstrap.properties:
`com.ibm.ws.logging.json.field.mappings=trace:ibm_userDir: ,ibm_datetime:`.

You can find more information by viewing link:https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html[Logging and Trace] on IBM Knowledge Center or on the link:https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html[Open Liberty Logging docs]

[#EPT]
=== Persistent EJB Timers coordination and failover across members

Prior to this feature, it was possible to partly coordinate automatic EJB persistent timers across multiple Open Liberty servers by configuring the EJB timer service to persist timers to the same database. This caused a single timer instance to be created on one of the servers but without the ability to to another server if the original server stops or crashes. To enable failover, this feature adds a new configurable attribute, `missedTaskThreshold`, which specifies the maximum amount of time that you want to allow for an execution of a persistent timer to complete before allowing another server to take over and run it instead.

Enable the EJB persistent timers feature, or another feature that implicitly enables it, such as `ejb-3.2` and configure it to use a data source. In this example, we let it use the Java EE or Jakarta EE default data source. This much is required regardless of whether failover is desired. To use failover,ensure that configuration for all servers is pointing at the same database and uses the same database schema. Then include a value for the `missedTaskThreshold` attribute.

Add the feature to the `server.xml`

[source, xml]
----
<server>
  <featureManager>
    <feature>ejbPersistentTimer-3.2</feature>
    <feature>jdbc-4.2</feature>
    ... other features
  </featureManager>

  <dataSource id="DefaultDataSource">
    <jdbcDriver libraryRef="OraLib"/>
    <properties.oracle URL="jdbc:oracle:thin:@//localhost:1521/EXAMPLEDB"/>
    <containerAuthData user="dbuser" password="dbpwd"/>
  </dataSource>
  <library id="OraLib">
    <file name="${shared.resource.dir}/jdbc/ojdbc8.jar" />
  </library>

  <!-- The following enables failover for persistent timers -->
  <persistentExecutor id="defaultEJBPersistentTimerExecutor" missedTaskThreshold="5m"/>

  ...
</server>
----


[#previews]
== Previews of early implementations available in development builds

You can now also try out early implementations of some new capabilities in the link:{url-prefix}/downloads/#development_builds[latest Open Liberty development builds]:

* <<GraphQL, GraphQL with Open Liberty >>

These early implementations are not available in 20.0.0.5 but you can try them out in our daily Docker image by running `docker pull openliberty/daily`. Let us know what you think!

[#GraphQL]
== You are now free to use GraphQL with Open Liberty!
In our latest OpenLiberty development builds, users can now develop and deploy GraphQL applications.  GraphQL is a complement/alternative to REST that allows clients to fetch or modify remote data, but with fewer round-trips.  Liberty now supports the (still under development) MicroProfile GraphQL APIs (link:https://github.com/eclipse/microprofile-graphql[learn more]) that allow developers to create GraphQL apps using simple annotations - similar to how JAX-RS uses annotations to create a RESTful app.

Developing and deploying a GraphQL app is cinch - take a look at this link:https://github.com/OpenLiberty/sample-mp-graphql[sample] to get started with these powerful APIs!


== Get Liberty 20.0.0.4 now

Available through <<run,Maven, Gradle, Docker, and as a downloadable archive>>.
