---
layout: post
title: "Setting HTTP Response Compression with Open Liberty"
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/28316667
author_github: https://github.com/mrsaldana
seo-title: Setting HTTP Response Compression with Open Liberty
seo-description: You can now specify in the server configuration which HTTP endpoints will consider compressing HTTP responses. HTTP response compression may be used to reduce bandwidth between HTTP clients and the server.
blog_description: You can now specify in the server configuration which HTTP endpoints will consider compressing HTTP responses. HTTP response compression may be used to reduce bandwidth between HTTP clients and the server.
---
= Setting HTTP Response Compression with Open Liberty
Manuel Saldana <https://github.com/mrsaldana>
:imagesdir: /
:url-prefix:
:bl: pass:[ +]
:star: pass:[*]
:add: pass:[+]


It is now possible to configure Open Liberty so that HTTP responses are considered for compression. By compressing the sizes of HTTP responses, bandwidth is reduced, which in turn decreases exchange times between HTTP clients and Open Liberty servers. Sounds good so far... but, what does the statement `_HTTP responses are considered for compression_` actually mean?

Once the Open Liberty server has had this feature enabled, there are _conditions_ that must be met for an HTTP response to be compressed.

== It All Starts With an HTTP Client ...

HTTP clients will specify which encoding algorithms they support, or do not support, by including an `Accept-Encoding` header in the HTTP request. The values provided by this header can optionally be accompanied by a quality value, ranging from `0.000-1.000`, which indicates a preference for the encoding. When the quality value is omitted for an encoding algorithm, the Open Liberty server will interpret it as having a value of `1.000`. On the other hand, a value of `0.000` indicates that the HTTP client does *not* support the algorithm. The use of the asterisk (`*`) symbol is supported to indicate all encoding algorithms not explicitly mentioned by the header.

For instance,

- An HTTP client may specify it supports the `gzip` and `deflate` algorithms by setting the following `Accept-Encoding` header:

  Accept-Encoding: gzip, deflate

- It could also specify that *any* encoding is supported:

  Accept-Encoding: *

- Or that `deflate` and `gzip` are both supported, but `gzip` is preferred:

  Accept-Encoding: deflate;q=0.5, gzip;q=1.0

- Or that `gzip` is preferred, `identity` is accepted, but *no* other encoding algorithm should be used:

  Accept-Encoding: gzip;q=1.0, identity; q=0.5, *;q=0

Armed with a list of encoding algorithms supported by the HTTP client, the server can now verify if there is an encoding algorithm that is supported *both* by the HTTP client and the Open Liberty server. However, there could be multiple encoding algorithms that match this criteria, `_so how does the server *choose* which encoding algorithm to use_`? On to the Open Liberty Server to find out!

== A Compression Enabled Open Liberty Server

Before making use of the `Accept-Encoding` header, the Open Liberty server will determine if it *should* compress by:

*Checking the response for a `Content-Encoding` header*:: It is possible that a filter or an application has already indicated that the response has been encoded. If this is the case, no further attempts to encode the body will be made.

*Checking the response for a `Content-Length` header*:: Values less than `2048` bytes are considered too small to benefit for compression. Therefore, if the content length is known, the server will ensure it is larger or equal to `2048` bytes.

*Checking the response for a `Content-Type` header*:: The configuration for this feature includes an attribute, called `types`, that defines which content types should be *included* and which should be *excluded* from compression consideration. The value indicated by this header must be both included and not excluded to be considered a valid candidate for compression. Find more information on this attribute on the <<Ready to Try Compression Yourself?>> section.

If the server determines that the response *should* be compressed,  it just needs to verify if it *can* be compressed. Which brings us back to the same question, `_how does the server *choose* which encoding algorithm to use_`? As mentioned before, the HTTP client specifies it supports an encoding algorithm by means of specifying it in the `Accept-Encoding` header.

However, this is not the only factor considered. In fact, there are three possible scenarios. The Open Liberty server will evaluate them, in order, until an encoding algorithm is obtained that is supported by *both* the HTTP client and by the Open Liberty server. If no encoding algorithm is found, or if the encoding algorithm is `identity`, then no compression will be attempted.

NOTE: Open Liberty supports the following encoding algorithms: `gzip`, `x-gzip`, `deflate`, `zlib`, `identity`.

The order used to choose which encoding algorithm to use is:


. *Using the `$WSZIP` private header*
{bl}
  Historically, Open Liberty only considered compression when this private header was used. The value for this header indicates the desired encoding algorithm.
{bl}
{bl}
. *Using the server's preferred algorithm*
{bl}
  The compression feature supports defining a server preferred algorithm by configuring the `serverPreferredAlgorithm` attribute. The value indicated by this attribute will be used as long as the `Accept-Encoding` header contains this name, be it implicitly or explicitly, with a quality value larger than `0.000`. This value will be used regardless of whether there are other higher ranked quality values in the `Accept-Encoding` header.
{bl}
{bl}
  For instance, consider the following header: `Accept-Encoding: deflate;q=0.5, gzip;q=1.0`
{bl}
{bl}
  Without defining a server preferred encoding, the server would pick `gzip`, as it is the highest ranked quality value in the list. However, if `deflate` were to be set as the server preferred encoding algorithm, the same `Accept-Encoding` header would result in `deflate` being chosen. Find more information on this attribute on the <<Ready to Try Compression Yourself?>> section.
{bl}
{bl}
. *Using the HTTP Clients preferred algorithm*
{bl}
The values for the `Accept-Encoding` header are sorted in descending order and each value is evaluated until a valid encoding is found. The highest ranked valid algorithm is chosen. If the `gzip` algorithm is tied among the highest ranked, it will be chosen as the algorithm to use. If there are no explicitly named encoding algorithms, and the asterisk (`{star}`) symbol is used, `gzip` will be used if able. If not able to use `gzip`, `deflate` will be used. If both are declared as unsupported by means of a quality value of `0.000`, no content encoding algorithm is chosen.
{bl}
{bl}
*For example, assuming the $WSZIP header and the server's preferred algorithm are not specified,*

     - The HTTP client can specify the preferred encoding algorithm as `gzip` by giving it the highest quality value.

    Accept-Encoding: deflate;q=0.5, gzip;q=1.0

      - The HTTP client can specify multiple encoding algorithms with the highest quality value. In such cases, the server will pick the `gzip` algorithm if able.

      Accept-Encoding: deflate;q=1.0, gzip;q=1.0

      - The HTTP client may also indicate all encodings are supported. Since the `gzip` algorithm is supported, the server will choose it.

      Accept-Encoding: *

      - The HTTP client can specify the `gzip` algorithm is *not* supported. In this case, the `deflate` algorithm is used instead.

      Accept-Encoding: gzip;q=0, *

      - The HTTP client can specify it does *not* support either the `gzip` or `deflate` algorithms. In this case, no compression algorithm will be chosen.

      Accept-Encoding: gzip;q=0, deflate;q=0, *


If no content encoding algorithm was chosen by the steps above, or if the encoding algorithm is set to `identity`, *no* compression will be realized on the response.

Additionally, since the `Accept-Encoding` header influences the Open Liberty's process for selecting and representing the response, a `Vary` header with the value of `Accept-Encoding` is also added to the response. This header informs cache intermediaries that this response’s content may change in a subsequent request if the `Accept-Encoding` header changes. The header will be added regardless of whether the response is ultimately compressed or not, as long as the compression feature is configured in the `server.xml`.

== Ready to Try Compression Yourself?

Great! To use the Http response compression support, you need *Open Liberty 20.0.0.4*. Configure the `server.xml` with a new element called `<compression>`.
This can be enabled in two modes:

 - A `<compression>` element for each `<httpEndpoint>` element

 - One common `<compression>` configuration used for multiple
`<httpEndpoint>` elements.

*Using a distinct <compression> for each <httpEndpoint>:*
[source,xml]
----
<httpEndpoint id="defaultHttpEndpoint"
                        httpPort="9080"
                        httpsPort="9443">
    <compression serverPreferredAlgorithm="deflate|gzip|x-gzip|zlib|identity|none>" types="list_of_types"/>
</httpEndpoint>
----

*Using a common `<compression>` element:*
[source, xml]
----
    <httpEndpoint id="defaultHttpEndpoint"
                        httpPort="9080"
                        httpsPort="9443"
                        compressionRef="myCompressionID">
    </httpEndpoint>

    <httpEndpoint id="otherHttpEndpoint"
                        httpPort="9081"
                        httpsPort="9444"
                        compressionRef="myCompressionID">
    </httpEndpoint>

    <compression id="myCompressionID" serverPreferredAlgorithm="deflate|gzip|x-gzip|zlib|identity|none>" types="list_of_types"/>
----

There are *two* optional attributes supported by this element:

  - *serverPreferredAlgorithm:*
{bl}
  By default, this is set to the value of `none`. However, when set to any of the other supported values, the corresponding encoding algorithm is utilized to encode the response whenever the HTTP client supports it, regardless of there being other higher weighted encoding algorithms in the `Accept-Encoding` header. The values supported by this attribute are: `deflate`, `gzip`, `x-gzip`, `zlib`, `identity`, and `none`.
{bl}
{bl}
  - *types:*
{bl}
  The `types` attribute is a comma delimited list of content types that are to be *included* or *excluded* from compression consideration. To include a content type to the default values, affix the add ({add}) character as a prefix to that content type. To exclude a content type from compression, affix the remove (-) character as a prefix to that content type.
{bl}
{bl}
  The wildcard (`{star}`) symbol is supported, but only as a content subtype, such as `text/{star}`. The default list has the values of `text/{star}, application/javascript`.
{bl}
{bl}
  *For example,*
{bl}
 * *Configuring `<compression types="-text/plain"/>`*
{bl}
{bl}
  Preserves the default of `text/{star}` and `application/javascript`, but will exclude any response whose content type is `text/plain` from being compressed.
{bl}
* *Configuring `<compression types="text/plain, application/{star}"/>`*
{bl}
{bl}
  Overwrites the default list. New list will include all application content types, `application/{star}`, and `text/plain`.
{bl}
* *Configuring `<compression types="{add}custom/{star}"/>`*
{bl}
{bl}
  Preserves the default of `text/{star}` and `application/javascript`, and adds all `custom/{star}` content types.

==  Configuration Pitfalls

If the HTTP transport encounters a configuration that is considered *invalid*, a warning message with an appropriate message will be logged. If this happens, the *default* value for the attribute that was misconfigured will be used.

Again, the *default* value for the `<compression>` element's attributes are:

- *serverPreferredAlgorithm:* `none`

- *types:* `text/{star}, application/javascript`

The following message keys are associated to *misconfigurations* of the `<compression>` element's attributes: `CWWKT0029W`, `CWWKT0030W`, `CWWKT0031W`, `CWWKT0032W`, and `CWWKT0033W`.

  - *CWWKT0029W*
{bl}
  This happens when there are entries in the `types` attribute list that try to use the add (+) option to include duplicate names.
{bl}
{bl}
For instance, configuring `<compression types=“{add}application/x-javascript, {add}application/x-javascript”/>` would result in the following message being logged:

    CWWKT0029W: A duplicate add of the application/x-javascript type was attempted. The text/*, application/javascript default configuration is used instead.
    types=“-application/x-javascript, -application/x-javascript”

  - *CWWKT0030W*
{bl}
This happens when there are entries in the `types` attribute list that try to use the remove (-) option to exclude duplicate names.
{bl}
{bl}
For instance, configuring `<compression types=“-application/x-javascript, -application/x-javascript”/>` would result in the following message being logged:

    CWWKT0030W: A duplicate removal of the application/x-javascript type was attempted. The text/*, application/javascript default configuration is used instead.


  - *CWWKT0031W*
{bl}
This happens when there are entries in the `types` attribute list that try use the add (+) and (-) remove options on the same content type value.
{bl}
{bl}
For instance, configuring `<compression types=“+application/x-javascript, -application/x-javascript”/>` would result in the following message being logged:

    CWWKT0031W: An attempt was made to both add and remove the same application/x-javascript content type. The text/*, application/javascript default configuration is used instead.

  - *CWWKT0032W*
{bl}
This happens when there are entries in the `types` attribute list that try to overwrite the default list, while also containing entries that try to use the add option.
{bl}
{bl}
For instance, configuring `<compression types=“application/xhtml+xml, {add}application/x-javascript”/>` would result in the following message being logged:

    CWWKT0032W: An attempt was made to overwrite the compression default configuration but also use the add (+) option on other content type(s). The text/*, application/javascript default configuration is used instead.

  - *CWWKT0033W*
{bl}
This happens when an unsupported value is set on the `serverPreferredAlgorithm` attribute. Suppose `deflated` was configured by accident, instead of the supported `deflate` value. In this scenario, the default value of `none` would be set and the following message logged:

    CWWKT0033W: An attempt was made to configure deflated as the server-preferred algorithm. The supported values are gzip, x-gzip, zlib, deflate, identity, and none. The default configuration none is used instead.


== Ready to Download?

Take a look at *Open Liberty 19.0.0.4* on our Downloads https://openliberty.io/downloads/[page].The Http Response Compression functionality has been designed from the following Open Liberty Epic: https://github.com/OpenLiberty/open-liberty/issues/7502[#7502].
The design is outlined within the Epic for more detailed reading.
