---
layout: post
title: "Open Liberty development mode for Gradle"
categories: blog
author_picture:
author_github: https://github.com/rzgry
seo-title: Open Liberty development mode for Gradle - OpenLiberty.io
seo-description: Develop Open Liberty applications quicker with Open Liberty development mode for Gradle.
blog_description: "Develop Open Liberty applications quicker with Open Liberty development mode for Gradle."
---
= Open Liberty development mode for Gradle
Ryan Zegray <https://github.com/rzgry>

Open Liberty development mode, or dev mode, now works with gradle projects. Open Liberty dev mode allows you to develop applications with any text editor or IDE by providing hot reload and deployment, on demand testing, and debugger support. Your code is automatically compiled and deployed to your running server, making it easy to iterate on your changes. You can run tests on demand or even automatically so that you can get immediate feedback on your changes. You can also attach a debugger at any time to debug your running application.

If you would like to give Gradle dev mode a try you can follow the steps in our https://github.com/OpenLiberty/demo-devmode[demo-devmode] sample project.

== Setting up the project

For Gradle projects, dev mode is run through the Liberty Gradle Plugin.  Specify the Liberty Gradle Plugin with version `3.0` or above in your project’s `build.gradle` file.
[source,xml]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0'
    }
}
----

== Starting dev mode

Start dev mode by running the following command in your project: `gradle libertyDev`

== Automatically recompiling and deploying to the running server

Once dev mode is started, source code changes are automatically compiled and deployed to the running server.  You can add new dependencies in your `build.gradle` file to be used for compilation.  Resources and server configuration changes are also picked up.  If any features are added to the `server.xml` file, they are installed automatically.

== Running tests automatically and on demand

To run tests on demand, press Enter in the terminal where dev mode is running.

To run tests automatically after every change, include the `--hotTests` parameter when starting dev mode.  For example: `gradle libertyDev --hotTests`

== Attaching a debugger

At any point during dev mode, you can attach a Java debugger to debug your application.  By default, the debug port is `7777`, but another port can be used and shown in the console output if the default port is not available.

== Stopping dev mode

You can quit dev mode at any time by pressing CTRL+C in the terminal, or type `q` and press Enter.

== Further reading

For more details on dev mode, see the documentation for the https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#libertydev-task[dev task of the Liberty Gradle Plugin].
