---
layout: post
title: Enhancements to distributed tracing in microservices with MicroProfile 2.1
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/3322532
seo-title: Enhancements to distributed tracing in microservices - OpenLiberty.io. 
seo-description: A quick roundup of some things you can try in the current Open Liberty development builds. Options to skip tracing of JAX-RS requests and using alternative formats of span names in MicroProfile OpenTracing 1.2. Also, try out writing simpler Dockerfiles by packaging your server as a TAR file, and try the support for sharding in Java 11 with JDBC 4.3.
blog_description: "A quick roundup of some things you can try in the current Open Liberty development builds. Options to skip tracing of JAX-RS requests and using alternative formats of span names in MicroProfile OpenTracing 1.2. Also, try out writing simpler Dockerfiles by packaging your server as a TAR file, and try the support for sharding in Java 11 with JDBC 4.3."
---
= Enhancements to distributed tracing in microservices with MicroProfile 2.1
Laura Cowen <http://github.com/lauracowen>

A quick roundup of a few of things you can try in the current https://openliberty.io/downloads/[Open Liberty development builds] (i.e. beta-level):

* <<mpopentracing,Enhancements to distributed tracing (MicroProfile OpenTracing 1.2)>>
* <<servertar,Package server TAR files for simpler Dockerfiles>>
* <<jdbc,Support for sharding in Java 11 (JDBC 4.3)>>


[#mpopentracing]
== Enhancements to distributed tracing (MicroProfile OpenTracing 1.2)

Distributed tracing enables users to see the flow of requests between microservices, including seeing which microservices have high latency and seeing the hierarchy of calls between applications and their dependent microservices.

In MicroProfile OpenTracing 1.2, you can now also:

* Skip tracing of JAX-RS requests by specifying a regular expression that matches `UriInfo.getPath()`
* Use an alternative format for span names. The new format is `<http method>:/@Path value of endpoint's class>/<@Path value of endpoint's method>`. For example, `GET:/inventory/list`

Enable the two new functions by defining two keys using MicroProfile Config (e.g. in `server.xml` or `bootstrap.properties`):

* `mp.opentracing.server.skip-pattern`
* `mp.opentracing.server.operation-name-provider`


See also:

* https://openliberty.io/guides/microprofile-opentracing.html[Enabling distributed tracing in microservices (guide)]
* https://openliberty.io/guides/microprofile-config.html[Configuring microservices (guide)]
* https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices (interactive guide]



[#servertar]
== Package server TAR files for simpler Dockerfiles

Liberty’s server package tool now supports packaging to `.tar` and `.tar.gz` files. The package tool has long supported generating to `.zip` and `.jar` files (and on z/OS `.pax`) but, until now, the most common packaging format on Linux hasn’t been an option.

So why now? It all relates to making Liberty work better with Docker. Docker’s `ADD` command has built-in support for extracting `.tar` files. Adding a server package to your Dockerfile is now really simple.

Instead of doing this:

[source]
----
   FROM open-liberty
   COPY defaultServer.zip /tmp/defaultServer.zip
   EXEC apt-get update && apt-get install unzip && unzip /tmp/defaultServer.zip /opt/ol/ && apt-get remove -y unzip && rm -rf /var/lib/apt/lists/*
----

you can now simply write:

[source]
----
   FROM open-liberty
   ADD defaultServer.tar.gz /opt/ol/
----


[#jdbc]
== Support for sharding in Java 11 (JDBC 4.3)

If your JDBC driver supports the 4.3 specification level, the JDBC 4.3 feature enables you to take advantage of new capabilities in JDBC 4.3, including requesting connections and support for sharding. This feature requires Java 11.

It is now possible to request connections for a specific sharding key and optionally, super sharding key, if your database supports sharding and provides a JDBC 4.3 compliant driver.

Enable the feature in your server configuration (`server.xml`):

[source,xml]
----
<featureManager>
  <feature>jdbc-4.3</feature>
  <feature>jndi-1.0</feature>
  ...
</featureManager>
----

Configure one or more data sources in the `server.xml` as you would with the prior version JDBC features. For example:

[source,xml]
----
<dataSource jndiName="jdbc/43datasource">
  <properties databaseName="sampledb" serverName="host1.rchland.ibm.com" portNumber="1234"/>
  <containerAuthData user="user1" password="pwd1"/>
</dataSource>
----

Use the data source from your application in your app:

[source,java]
----
@Resource(lookup = "jdbc/43datasource")
DataSource datasource;
// Always cache sharding keys to ensure that matching of pooled connections can be successful.
// The JDBC spec does not require an .equals implementation.
ShardingKey key1, key2;
...
public void init(ServletConfig config) throws ServletException {
    try {
        key1 = datasource.createShardingKeyBuilder().subkey("key1", JDBCType.VARCHAR).build();
        key2 = datasource.createShardingKeyBuilder().subkey("key2", JDBCType.VARCHAR).build();
    } catch (SQLException x) {
        throw new ServletException(x);
    }
}
...
try (Connection con = datasource.createConnectionBuilder().shardingKey(key1).build()) {
    // use connection
}
----

See also:

* https://www.jcp.org/aboutJava/communityprocess/mrel/jsr221/index3.html[JDBC 4.3 specification]
* https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/package-summary.html[JDBC 4.3 JavaDoc]


== Try it now in development builds of Open Liberty

Take a look at the latest https://openliberty.io/downloads/[Open Liberty development builds].