---
layout: post
title: New 4-weekly release schedule with Open Liberty 19.0.0.1
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/1906689
seo-title: New 4-weekly release schedule with Open Liberty 19.0.0.1 - OpenLiberty.io.
seo-description: In Open Liberty 19.0.0.1, we are moving from our previous 3-monthly release cycle to a new 4-weekly release cycle. Alasdair, Open Liberty architect, explains what this means.
blog_description: "In Open Liberty 19.0.0.1, we are moving from our previous 3-monthly release cycle to a new 4-weekly release cycle. Alasdair, Open Liberty architect, explains what this means."
---
= New 4-weekly release schedule with Open Liberty 19.0.0.1
Alasdair Nottingham <https://github.com/nottycode>

Today, we released https://openliberty.io/downloads/[Open Liberty 19.0.0.1], the first release of 2019, and (you may have noticed) it's coming out much earlier in the year than our first release of 2018.  This is because the 19.0.0.1 release is the start of a brand new 4-week release cycle that we're moving to this year.  Four week release cycle, you say?  Why the change?  In order to understand the change, you need a little bit of history of why we were previously on a quarterly schedule.  Most of the contributors on the https://github.com/openliberty/open-liberty[open source Open Liberty project] are employed by IBM, and our historic organization and practices influence how the project is run, sometimes in non-obvious ways. One of the things that is influenced by this has been the release dates and release cadence for https://openliberty.io/about/[Open Liberty].

Open Liberty's downstream IBM product, https://www.ibm.com/uk-en/marketplace/java-ee-runtime/purchase[WebSphere Liberty], has been producing quarterly fixpacks since its inception. When we first launched Open Liberty in September 2017, we tied the release dates together to help us manage the release more efficiently, and also to ensure that WebSphere Liberty customers get improvements released in Open Liberty as quickly as possible.

Four releases a year seemed like a reasonable release cadence but, a few things have made us rethink this. Developers doing continuous delivery typically receive Liberty through https://mvnrepository.com/artifact/io.openliberty[Maven Central] where fixes or new function requires a new release. If you are doing continuous delivery you are typically able to frequently consume new versions of software to pick up new function and fixes and you don't want to have to wait three months for something you need. In addition there has been an increase in focus on security issues and the need to consume fixes as quickly as possible. Getting a security fix is possible at any time for users paying for WebSphere Liberty or a https://openliberty.io/support/[support contract for Open Liberty], but if you are receiving the driver through https://mvnrepository.com/artifact/io.openliberty[Maven Central] or https://hub.docker.com/_/open-liberty[Docker Hub] things get a little more difficult. You don't want to wait three months for a zero day fix (not that we have had any). You can't just "replace" something in Maven Central, you have to do another release.

For 2019, we have decided that we need to provide more releases and for them to be more predictable. As a result, we have simplified the packaging and red tape around building releases and we are moving to a model where we release Open Liberty every four weeks rather than once every three months. This means each release will be smaller, with fewer changes, but you  will get functional and security fixes more often and more reliably. If you do the maths you will notice this means we should have 13 releases in a year rather than four (52/3=13). However, as the the first release is in February this year there will be only 12 in 2019.

There is no need to keep current if you do not wish to, although we obviously encourage it. We have been able to switch to this model because we have been busy building better and more reliable automation to reduce the time between an iteration ending and getting a golden master and then publishing it without reducing the quality of the releases.

We hope you like 19.0.0.1, and the new release cadence. If you would like to know more please let us know on twitter https://twitter.com/openLibertyIO/[@OpenLibertyIO] or https://twitter.com/nottycode[@NottyCode], or send an email to the https://groups.io/g/openliberty[Open Liberty mailing list].

_Thanks to Gary Picher for his contributions to this post._
