---
layout: post
title: "TITLE"
categories: blog
author_picture: https://avatars3.githubusercontent.com/GITHUB_USERNAME
author_github: https://github.com/GITHUB_USERNAME
seo-title: TITLE - makes sure it ends with - OpenLiberty.io
seo-description: DESCRIPTION
blog_description: DESCRIPTION
---
= TITLE
AUTHOR_NAME <https://github.com/GITHUB_USERNAME>
:imagesdir: /
:url-prefix:
:url-about: /
// // // // // // // //
// Above:
// Do not insert any blank lines between any of the lines above.
// Do not remove or edit the variables on the lines beneath the author name.
//
// Replace TITLE with the blog post title eg: MicroProfile 3.3 is now available on Open Liberty 20.0.0.4
// Replace GITHUB_USERNAME with your GitHub username eg: lauracowen
// Replace DESCRIPTION with a short summary (~60 words) of the release (a more succinct version of the first paragraph of the post).
// Replace AUTHOR_NAME with your name as you'd like it to be displayed, eg: Laura Cowen
// // // // // // // //

BETA_RELEASE_SUMMARY

// // // // // // // //
// Change the RELEASE_SUMMARY to a quick sentence intro. Make sure to keep the blank lines 
// // // // // // // //
We have two beta packages for link:{url-about}[Open Liberty]:

* <<allbeta, All Beta Features>>: a new, larger package that contains all Open Liberty beta and GA features and functions.
* <<jakarta, Jakarta EE 9 Beta Features>>: a lightweight package that contains only the Jakarta EE 9 features.

This means that you can now try out our in-development Open Liberty features by just adding the relevant coordinates to your build tools (either the Jakarta EE 9 Beta Features package or the All Beta Features package, depending on what you want to try).

If you try either package, <<feedback, let us know what you think>>.

[#allbeta]
== All Beta Features package

As well as the Jakarta EE 9 features listed above, the new All Beta Features package contains our new FEATURES features which have been available in our link:/downloads/#development_builds[nightly builds] for a few weeks but are now easy to install from Maven Central too.
// // // // // // // //
// Above:
// Change FEATURES to a feature that is included in this release     // version.
// // // // // // // //

[#SUB_TAG_1]
=== SUB_FEATURE_TITLE

// // // // // // // //
// FURTHER EXPLENATION OF THE FEATURE/CHANGE ABOVE
// // // // // // // //



[source, java]
----
// // // // // // // //
// EXAMPLE CODE
// // // // // // // //
----


To enable the new beta features in your app, add them to your `server.xml`:

[source, xml]
----

----

=== Try it now section for the feature 

// // // // // // // //
// how to try it now
// // // // // // // //

[source,xml]
----
<dependency>
  <groupId>io.openliberty.beta</groupId>
  <artifactId>openliberty-runtime</artifactId>
  <version>20.0.0.RELEASE_VERSION-beta</version>
  <type>pom</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty.beta', name: 'openliberty-runtime', version: '[20.0.0.RELEASE_VERSION-beta,)'
}
----

Or take a look at our link:{url-prefix}/downloads/#runtime_betas[Downloads page].

[#jakarta]
== Jakarta EE 9 Beta Features package

The main change visible to developers in the Jakarta EE 9 planned release is the names of packages changing to accomodate the new `jakarta.*` namespace. In this Open Liberty beta, we have more Jakarta EE 9 features with their name change completed. We've also made excellent TCK progress with these features.
// // // // // // // //
// ABOVE:
// Update the second and third sentence appropriately for this release
// // // // // // // //

This Open Liberty beta introduces the following Jakarta EE 9 features which now possess their all-new Jakarta EE 9 package names:

* ITEM_1
* ITEM_2
* ITEM_3
// // // // // // // //
// ABOVE:
// Change the ITEMS above to list the new changes and features in this
// beta release
// // // // // // // //


These join the Jakarta EE 9 features in link:https://openliberty.io/blog/?search=beta&key=tag[previous Open Liberty betas]:

// // // // // // // //
// Copy feature from both lists in the previous beta post creating    // a cumulative list from all previous betas to make a list of all    // existing features in the new beta.
// // // // // // // //

=== Try it now

To try out these Jakarta EE 9 features on Open Liberty in a lightweight package, just update your build tools to pull the Open Liberty Jakarta EE 9 Beta Features package instead of the main release. The beta works with Java SE 14, Java SE 11, or Java SE 8.

If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty.beta</groupId>
    <artifactId>openliberty-jakartaee9</artifactId>
    <version>20.0.0.RELEASE_VERSION-beta</version>
    <type>zip</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty.beta', name: 'openliberty-jakartaee9', version: '[20.0.0.RELEASE_VERSION-beta,)'
}
----
// // // // // // // //
// Above:
// Replace RELEASE_VERSION with the version number of Open Liberty
// // // // // // // //
Or take a look at our link:{url-prefix}/downloads/#runtime_betas[Downloads page].

Enable the Jakarta EE 9 beta features in your app's `server.xml`. You can enable the individual features you want (but remember if you enable the `jsp-3.0` feature, the `servlet-5.0` and `el-4.0` features are automatically enabled for you) or you can just add the Jakarta EE 9 convenience feature to enable all of the Jakarta EE 9 beta features at once:

[source, xml]
----
  <featureManager>
    <feature>jakartaee-9.0</feature>
  </featureManager>
----

Or you can add the Web Profile convenience feature to enable all of the Jakarta EE 9 Web Profile beta features at once:

[source, xml]
----
  <featureManager>
    <feature>webProfile-9.0</feature>
  </featureManager>
----


[#feedback]
== Your feedback is welcomed

Let us know what you think on link:https://groups.io/g/openliberty[our mailing list]. If you hit a problem, link:https://stackoverflow.com/questions/tagged/open-liberty[post a question on StackOverflow]. If you hit a bug, link:https://github.com/OpenLiberty/open-liberty/issues[please raise an issue].


