---
layout: post
title: "MicroProfile – The Natural Evolution for Microservices Development"
date:   2018-11-05 15:00:00 -0000
categories: blog
author_picture: https://avatars0.githubusercontent.com/u/7726127
author_github: https://github.com/kwsutter
seo-title: MicroProfile – The Natural Evolution for Microservices Development - OpenLiberty.io
seo-description: The Eclipse MicroProfile project allows you to leverage your existing Enterprise Java skills while moving to the cloud-native microservices architecture.
blog_description: "The Eclipse MicroProfile project allows you to leverage your existing Enterprise Java skills while moving to the cloud-native microservices architecture."
---
= MicroProfile – The Natural Evolution for Microservices Development
Kevin Sutter <https://github.com/kwsutter>
:imagesdir: /
:url-prefix:
:url-about: /

With the introduction of the link:https://bit.ly/mp-biz-ebook[“Eclipse MicroProfile: Accelerating Cloud-Native Application Development with Java Microservices” eBook], the Eclipse Foundation clearly explains how MicroProfile is the natural Java framework for microservices development.
Enterprise Java developers don’t have to “start over” just because they are moving to the newer microservices architecture.
They can build upon the knowledge and experience they have honed over the years with Java SE and EE.

But, how does one get started with MicroProfile?
link:{url-prefix}[Open Liberty] has been one of the leading open-source implementations of the MicroProfile platform.
Ever since the first MicroProfile 1.0 release in 2016, Open Liberty has provided a fully-compatible, production-ready implementation soon after the community completes the respective specifications.
This quick delivery cadence by Open Liberty allows you to experiment with new MicroProfile APIs almost as soon as they are defined.
The link:{url-prefix}/downloads/[latest Open Liberty deliverable] supports both MicroProfile 1.4 (based on Java EE 7) and 2.0 (based on Java EE 8).

Whether you are interested in just one MicroProfile technology or several, the link:https://www.openliberty.io/guides/[Open Liberty Guides] provide an excellent place to start.
Searching on a specific topic (ie. "Config" or "Fault Tolerance") or the full platform (ie. "MicroProfile") will provide a list of available Guides that will quickly get you up-to-speed on the respective technology.
The Guides are provided in either an interactive or “static” mode.
The interactive guides are web-based live code examples with no dependencies on a development environment.
The static guides are more “real” in the developer sense that you will use git, maven, and an editor to learn the technology.
You can use whichever approach is most comfortable.

I encourage you to learn about the advantages of link:https://microprofile.io[MicroProfile] as you move towards the microservices programming model.
And, I also encourage you to check out link:{url-prefix}[Open Liberty] -- a leading MicroProfile implementation.
