---
layout: post
title: "Jakarta EE 9 data source access and transactions in Open Liberty beta"
categories: blog
author_picture: https://avatars3.githubusercontent.com/lauracowen
author_github: https://github.com/lauracowen
seo-title: Jakarta EE 9 data source access and transactions in Open Liberty beta - OpenLiberty.io
seo-description: Our second Open Liberty beta makes available another three Jakarta EE 9 features (JDBC 4.2 & 4.3, JSON-B 2.0, JSON-P 2.0) and support for Java Transaction API (JTA) 2.0, plus JNDI 1.0. This is in addition to the three features we beta'd in the first Open Liberty beta (Servlet 5.0, JSP 3.0, Expression Language 4.0).
blog_description: Our second Open Liberty beta makes available another three Jakarta EE 9 features (JDBC 4.2 & 4.3, JSON-B 2.0, JSON-P 2.0) and support for Java Transaction API (JTA) 2.0, plus JNDI 1.0. This is in addition to the three features we beta'd in the first Open Liberty beta (Servlet 5.0, JSP 3.0, Expression Language 4.0).
additional_authors: 
- name: Kevin Sutter
  github: https://github.com/kwsutter
  image: https://avatars0.githubusercontent.com/kwsutter
---
= Jakarta EE 9 data source access and transactions in Open Liberty beta
Laura Cowen <https://github.com/lauracowen>
:imagesdir: /
:url-prefix:
:url-about: /about/

In no time at all, we have a second Open Liberty beta which makes available another four Jakarta EE 9 features (JDBC 4.2 & 4.3, JTA 2.0, JSON-B 2.0, JSON-P 2.0), plus JNDI 1.0. This is in addition to the three features we beta'd in the link:/blog/2020/06/22/jakarta-ee-9-open-liberty-20007beta.html[first Open Liberty beta] (Servlet 5.0, JSP 3.0, Expression Language 4.0).

== Jakarta EE 9: behind the scenes

As we mentioned in our link:/blog/2020/06/22/jakarta-ee-9-open-liberty-20007beta.html[first beta blog post], the most visible change to developers between Jakarta EE 8 and Jakarta EE 9 is the new namespace: `javax.\*` package names are now `jakarta.*` throughout the Jakarta EE 9 features. Behind the scenes, however, the Jakarta EE 9 project team have been working hard on changes to support Jakarta EE now and in future.

The list of specifications in Jakarta EE 9 has been modified since Jakarta EE 8. A subset of specifications that was part of Java SE 8 has been link:https://openjdk.java.net/jeps/320[moved into Jakarta EE 9] instead. Some Jakarta 8 specifications have been removed from Jakarta EE 9, while other specifications from Jakarta EE 8 have been marked optional in Jakarta EE 9. This is intended to lower the bar of entry to new implementations by removing "stable" or legacy specifications, or at least making them optional so that application servers can be link:https://jakarta.ee/compatibility/[certified as compatible] without necessarily supporting them.

If you're interested in reading the Jakarta EE 9 specifications, there are now specifications, APIs, TCKs, and Compatible Implementations (CIs) for every specification. From the link:https://jakarta.ee/specifications/[top-level specifications], you can navigate to any of the technologies to view their deliverables for their respective Milestone 1 releases. For example, here are the link:https://jakarta.ee/specifications/platform/9/[overall Jakarta EE 9 Platform] and link:https://jakarta.ee/specifications/cdi/3.0/[Jakarta Context Dependency Injection (CDI) 3.0] specifications.

In terms of progress, link:https://jakarta.ee/specifications/platform/9/[Jakarta EE 9 Milestone 1] was a great achievement but there's still some way to go. The APIs are close to being finalized. Many of the component specifications are brand new from a Jakarta EE perspective so there is still some polishing required yet. All of the TCKs are buildable and executable but the success rate is variable, depending on the specific Jakarta EE technology being exercised. This is expected at this point in the game and will make progress every day. All of the link:https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/53/junit-reports-with-handlebars/testSuitesOverview.html[TCK executions are on public Jenkins instances] and can be monitored. Or, better yet, they always welcome more community help so, link:https://eclipse-ee4j.github.io/jakartaee-tck/[if you're interested, get involved].

Every specification and associated TCK requires a Compatible Implementation (CI) to show completeness.  For the Jakarta EE 9 Milestone 1 deliverable, link:https://github.com/eclipse-ee4j/glassfish/releases/tag/6.0.0-M1[Eclipse Glassfish 6.0.0-M1] fulfills that role. But, as with Jakarta EE 8, there will be additional CIs for Jakarta EE 9, including link:{url-about}[Open Liberty].

We will demonstrate our on-going progress implementing Jakarta EE 9 on Open Liberty through our regular beta releases, now every 4 weeks.

== Jakarta EE 9 features on Open Liberty

This beta of Open Liberty implements Java Database Connectivity (JDBC) integration with Java Transaction API (JTA), JSON-B 2.0 and JSON-P 2.0, plus JNDI 1.0. JNDI is not part of Jakarta EE 9 but it's included to enable the use of data sources and transactions within applications. When added to the existing Jakarta EE 9 features, this means it is now possible to configure Servlet 5.0, JDBC 4.3 (on Java 11; JDBC 4.2 on Java 8), and JNDI 1.0 so that you can configure your applications to both access data sources and participate in global transactions.

The JSON-B and JSON-P features will come into their own when we finish JAX-RS in a future beta. So keep an eye on link:/blog/?search=beta[future beta blog posts].

== Try it now

If you want to get started with the beta just update your build tools to pull the Open Liberty beta instead of the main release. The beta works with Java SE 11 or Java SE 8.

If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty.beta</groupId>
    <artifactId>openliberty-jakartaee9</artifactId>
    <version>20.0.0.8-beta</version>
    <type>zip</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty.beta', name: 'openliberty-jakartaee9', version: '[20.0.0.8-beta,)'
}
----

//end::run[]

Or take a look at our link:{url-prefix}/downloads/#runtime_betas[Downloads page].

To enable the new beta features in your app, add one or more of them to your `server.xml` (if you enable the `jsp-3.0` feature, the `servlet-5.0` and `el-4.0` features are automatically enabled so you don’t need to explicitly list all three in that case):

Add the features to the `server.xml`:

[source, xml]
----
<featureManager>
  <feature>jdbc-4.2</feature>
  <feature>jsonb-2.0</feature>
  <feature>jsonp-2.0</feature>
  <feature>jndi-1.0</feature>
  <feature>jsp-3.0</feature>
  <feature>servlet-5.0</feature>
  <feature>el-4.0</feature>
</featureManager>
----

Alternatively, you can just enable the Jakarta EE 9 convenience feature to enable them all at once:

[source, xml]
----
<server>
  <featureManager>
    <feature>jakartaee-9.0</feature>
  </featureManager>
</server>
----

Let us know what you think on link:https://groups.io/g/openliberty[our mailing list]. If you hit a problem, link:https://stackoverflow.com/questions/tagged/open-liberty[post a question on StackOverflow]. If you hit a bug, link:https://github.com/OpenLiberty/open-liberty/issues[please raise an issue].


_Kevin is a co-Release Lead for the link:https://jakarta.ee/[Jakarta EE 9 project], working with the wider community to help ensure that a cohesive specification is delivered and represents the expectations of the link:https://jakarta.ee/about/[Jakarta EE Working Group]. Laura is Content Strategist for Open Liberty and Editor of this blog._

