---
layout: post
title: "Choose whether to disable LTPA or JWT cookies on Open Liberty 20.0.0.7"
categories: blog
author_picture: https://avatars3.githubusercontent.com/tomjenningss
author_github: https://github.com/tomjenningss
seo-title:Choose whether to disable LTPA or JWT cookies on Open Liberty 20.0.0.7 - OpenLiberty.io
seo-description: Choose whether to disable LTPA or JWT cookies on Open Liberty 20.0.0.7
blog_description: Choose whether to disable LTPA or JWT cookies on Open Liberty 20.0.0.7
---
= Choose whether to disable LTPA or JWT cookies on Open Liberty 20.0.0.7
Tom Jennings <https://github.com/tomjenningss>
:imagesdir: /
:url-prefix:
:url-about: /about/

// tag::intro[]

With Open Liberty 20.0.0.7 users have the availability to configure the return cookies for LPTA TAI/SPNEGO or JWT cookies.

In link:{url-about}[Open Liberty] 20.0.0.7:

* <<LTPA-cookie, Configure for LTPA TAI/SPNEGO or JWT cookies>>

View the list of fixed bugs in link:https://github.com/OpenLiberty/open-liberty/issues?q=label%3Arelease%3A20007+label%3A%22release+bug%22+[20.0.0.7].

If you're interested in what's coming soon in Open Liberty, take a look at our <<previews,current development builds>> which include gRPC with Open Liberty.
// end::intro[]

// tag::run[]
[#run]

== Run your apps using 20.0.0.7

If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty</groupId>
    <artifactId>openliberty-runtime</artifactId>
    <version>20.0.0.7</version>
    <type>zip</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty', name: 'openliberty-runtime', version: '[20.0.0.7,)'
}
----

Or if you're using Docker:

[source]
----
FROM open-liberty
----
//end::run[]

Or take a look at our link:{url-prefix}/downloads/[Downloads page].

[link=https://stackoverflow.com/tags/open-liberty]
image::img/blog/blog_btn_stack.svg[Ask a question on Stack Overflow, align="center"]

//tag::features[]

[#LTPA-cookie]
=== Choose to disable LTPA cookie for TAI/SPNEGO or JWT cookies

LTPA cookie serves as an authentication token containing the user identity, key and token data, buffer length, and expiration information. Users now have the option to decide the type of cookie to return, the default SSO LTPA cookie or SSO JWT cookie.

When a browser client is authenticated with a Open Liberty server, the default response is the single sign-on (SSO) LTPA cookie in the HTTP servlet. When the same browser client accesses another protected resource with the same or different Open Liberty server, authentication with SSO LTPA cookie will happen first before any other authentication mechanism. This can potentially can cause problems for users who want to use JWT SSO cookie for authentication instead of SSO LTPA. The update allows users to either disable either LTPA cookie for TAI/SPNEGO through `spnego-1.0` feature or JWT cookie for `jwtSso-1.0` feature.

Adding the `jwtSso-1.0` feature will return SSO JWT cookies in the HTTP servlet, not LTPA for TAI/SPNEGO.

Add the feature to the `server.xml`:

[source, xml]
----
<server>
  <featureManager>
    <feature>jwtSso-1.0</feature>
  </featureManager>
</server>
----

When a browser client is authenticated with the Open Liberty server that has the `jwtSso-1.0` feature enabled, the Open Liberty server returns the single sign-on (SSO) JWT cookies in the HTTP servlet response. When the same browser client accesses another protected resource with the same or different Open Liberty server, authentication with SSO JWT cookie happens before any other authentication mechanism.

//end::features[]

[#previews]
== Previews of early implementations available in development builds

You can now try out the new gRPC and gRPC Client.

gRPC is a high-performance, open source universal RPC framework. gRPC support on Liberty allows developers to both provide and consume gRPC services from their web applications. The introduction of gRPC support in OpenLiberty now means developers can take advantage of the benefits of gRPC more easily than before. Those benefits include great performance, simple service definitions via Protocol Buffers, cross-platform and language support, and wide industry adoption.

Two new features are available in beta: `grpc-1.0`, which enables gRPC services, and `grpcClient-1.0`, which enables the use of a gRPC client for outbound calls.

Add the features to the `server.xml`:

[source, xml]
----
<server>
  <featureManager>
    <feature>grpc-1.0</feature>
    <feature>grpcClient-1.0</feature>
  </featureManager>
</server>
----

The `grpc-1.0` feature works by scanning web apps for gRPC service implementations, through implementors of `io.grpc.BindableService`. The webapp must include the protocol buffer compiler generated code for the services it intends to provide, and additionally the service class must provide a no-argument constructor. The webapp does not need to include any core gRPC libraries; those are provided by the Liberty runtime. Once a gRPC service is scanned and started, it becomes accessible to remote gRPC clients on the configured HTTP ports.

The `grpcClient-1.0` feature provides applications with access to a Netty gRPC client, as well as the related libraries. A webapp must provide a client implementation and stubs, and can make outbound calls with a io.grpc.ManagedChannel without needing to provide the supporting client libraries.

Try out gRPC through a basic helloworld service by defining `grpc-1.0` within the `server.xml`:

[source, java]
----
package com.ibm.ws.grpc;

import com.ibm.ws.grpc.beans.GreetingBean;

import io.grpc.examples.helloworld.GreeterGrpc;
import io.grpc.examples.helloworld.HelloReply;
import io.grpc.examples.helloworld.HelloRequest;
import io.grpc.stub.StreamObserver;

public class HelloWorldService extends GreeterGrpc.GreeterImplBase {

    public HelloWorldService(){}

    @Override
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
        HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + req.getName()).build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
    }
}
----

For this example, the application must provide the link:https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/helloworld.proto[helloworld protof definition] along with the protobuf compiler output. No additional libraries need to be provided with the application, and once it's started the helloworld Greeter service will be accessible on the server's HTTP endpoints.

For a client example, a basic Servlet using gRPC can be defined via grpcClient-1.0 with:

[source, java]
----
package com.ibm.ws.grpc;

import io.grpc.examples.helloworld.GreeterGrpc;
import io.grpc.examples.helloworld.HelloReply;
import io.grpc.examples.helloworld.HelloRequest;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
...
@WebServlet(name = "grpcClient", urlPatterns = { "/grpcClient" }, loadOnStartup = 1)
public class GrpcClientServlet extends HttpServlet {

        ManagedChannel channel;
        private GreeterGrpc.GreeterBlockingStub greetingService;

        private void startService(String address, int port) 
        {
            channel = ManagedChannelBuilder.forAddress(address , port).usePlaintext().build();
            greetingService = GreeterGrpc.newBlockingStub(channel);
        }

        private void stopService() 
        {
            channel.shutdownNow();
        }

        @Override
        protected void doGet(HttpServletRequest reqest, HttpServletResponse response) 
            throws ServletException, IOException 
        {

            // set user, address, port params
        }

        @Override
        protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException 
        {

        // grab user, address, port params
        startService(address, port);
        HelloRequest person = HelloRequest.newBuilder().setName(user).build();
        HelloReply greeting = greetingService.sayHello(person);

        // send the greeting in a response
        stopService();
        }	
    }
}
----

As with the service example, the application must provide the link:https://github.com/grpc/grpc-java/blob/master/examples/src/main/proto/helloworld.proto[helloworld protof definition] along with the protobuf compiler output. All required gRPC client libraries are provided by `grpcClient-1.0`.

== Get Open Liberty 20.0.0.7 now

Available through <<run,Maven, Gradle, Docker, and as a downloadable archive>>.