---
layout: post
title: "New features for MicroProfile 4.0 and more Jakarta EE 9 features in Open Liberty 20.0.0.10 beta"
categories: blog
author_picture: https://avatars3.githubusercontent.com/jakub-pomykala
author_github: https://github.com/jakub-pomykala
seo-title: New features for MicroProfile 4.0 and more Jakarta EE 9 features in Open Liberty 20.0.0.10 beta - OpenLiberty.io
seo-description: Open Liberty 20.0.0.10 beta comes with new features for MicroProfile 4.0 and more Jakarta EE 9 features. Give it a try by adding either Jakarta EE 9 Beta features package coordinates or the All Beta features package coordinates to your build tools.
blog_description: Open Liberty 20.0.0.10 beta comes with new features for MicroProfile 4.0 and more Jakarta EE 9 features. Give it a try by adding either Jakarta EE 9 Beta features package coordinates or the All Beta features package coordinates to your build tools.
---
= TITLE
Jakub Pomykala <https://github.com/jakub-pomykala>
:imagesdir: /
:url-prefix:
:url-about: /about/

In this release of Open Liberty Beta you can try the new features for MicroProfile 4.0 which are Fault Tolerance 3.0, Matric 3.0, Health 3.0 and OpenTracing 2.0 plus more Jakarta EE 9 features.

We have two beta packages for link:{url-about}[Open Liberty]:

* <<jakarta, Jakarta EE 9 Beta Features>>: a lightweight package that contains only the Jakarta EE 9 features.
* <<allbeta, All Beta Features>>: a new, larger package that contains all Open Liberty beta and GA features and functions.

This means that you can now try out our in-development Open Liberty features by just adding the relevant coordinates to your build tools (either the Jakarta EE 9 Beta Features package or the All Beta Features package, depending on what you want to try).

If you try either package, <<feedback, let us know what you think>>.
[#allbeta]
== All Beta Features package

* <<fault, MicroProfile Fault Tolerance 3.0>>
* <<metric, MicroProfile Metric 3.0>>
* <<health, MicroProfile Health 3.0>>
* <<opentracing, MicroProfile OpenTracing 2.0>>
* <<jakarta, Jakarta EE 9 Beta Features package>>

As well as the Jakarta EE 9 features listed above, a new, larger package that contains all Open Liberty beta features (including Jakarta EE 9 beta features) and GA features and functions. The new features included are MicroProfile Fault Tolerance 3.0, MicroProfile Metrics 3.0, MicroProfile Health 3.0 and MicroProfile OpenTracing 2.0 features which have been available in our link:/downloads/#development_builds[nightly builds] for a few weeks but are now easy to install from Maven Central too.

[#fault]
=== MicroProfile Fault Tolerance 3.0

MicroProfile Fault Tolerance allows developers to easily apply strategies for mitigating failure to their code. It provides annotations which developers can add to methods to use bulkhead, circuit breaker, retry, timeout and fallback strategies.

Fault Tolerance 3.0 overhauls the metrics automatically exported by Fault Tolerance to take advantage of metric tags to make it easier to use those metrics to understand when and where your application is failing.

Information which was previously included in the metric name is now included as metric tags, making it much easier to query for data from multiple methods and pick out which, if any, is causing issues.

Example:

Old metric: `application:ft.<name>.timeout.callsTimedOut.total`

New metric: `base:ft.timeout.calls.total{method="<name>", timedOut="true"}``


==== Try it now 

Enable Fault Tolerance 3.0 and CDI in the server.xml, along with any other features you're using.

[source, xml]
----
<featureManager>
  <feature>mpFaultTolerance-3.0</feature>
  <feature>cdi-2.0</feature>
  <feature>jaxrs-2.1</feature>
</featureManager>
----

Add any of the Fault Tolerance annotations to a business method of a CDI bean.

[source, java]
----
@Retry(5)
public User lookupUserFromRegistry(String name) {
  return registry.getUser(name);
}
----

When that method is called as a a CDI business method, the fault tolerance strategy will be used. In this example, if `lookupUserFromRegistry()` would throw an exception, it will instead be retried up to five times.

Get an introduction to MicroProfile Fault Tolerance with the Open Liberty guides:

* link:https://openliberty.io/guides/retry-timeout.html[Failing fast and recovering from errors]
* link:https://openliberty.io/guides/circuit-breaker.html[Preventing repeared failed calls to microservices]

References to:

* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/apidocs/[Java]

* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/microprofile-fault-tolerance-spec.html[Full Specification]

* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/microprofile-fault-tolerance-spec.html#_integration_with_microprofile_metrics[New format for metrics in detail in Chapter 11]

link:https://github.com/OpenLiberty/open-liberty/[Report any issues on Github]


[#metric]
=== MicroProfile Metric 3.0

MicroProfile Metrics 3.0 (as part of MicroProfile 4.0) introduces new metric values for the existing SimpleTimer and Timer metrics. Additionally a new REST metric is introduced for better monitoring and handling of unmapped exceptions. Manual configuration for re-usability has been removed. A notable change to the MP Metrics programming model regarding CDI Producers has been made. Lastly a medley of API improvements and refactoring have been added in this release.

==== SimpleTimer
The SimpleTimer metric now tracks and reports the highest and lowest recorded time duration of the previous complete minute. See the SimpleTimer.java for more more information in the Javadoc.

==== Timer
The Time metric now tracks and reports the total elapsed time duration. See the Tiimer.java for more information in the Javadoc.

==== REST metric
A new REST.request.unmappedException.total metric that is backed by a counter metric has been introduced. Similar to the REST.request metric, there will be one unique metric for each REST endpoint identified by a class and method label. The new REST metric will count the amount of times the request ends in an unmapped exception. The REST.request metric corresponding to this REST endpoint will not record any values if an unmapped exception has occured.

==== CDI Producer
The @Metrics annotation will no longer support the method target (i.e it can not be annotated on a method). Additionally, it will not support usage with CDI Producers.

==== Try it now 

Enable Metrics 3.0 in the server.xml, along with any other features you're using.

[source, xml]
----
<featureManager>
    <feature>mpMetrics-3.0</feature>
</featureManager>
----

More information:

* link:https://github.com/eclipse/microprofile-metrics/releases/tag/3.0-RC1[MicroProfile Metrics 3.0 Release Page]

* link:https://github.com/eclipse/microprofile-metrics/blob/3.0-RC1/spec/src/main/asciidoc/changelog.adoc[Release Notes]


[#health]
=== MicroProfile Health 3.0

MicroProfile Health 3.0 enables you to provide your own health check procedures to be invoked by Open Liberty, to verify the health of your microservice.

MicroProfile Health allows services to report their health, and it publishes the overall health status to a defined endpoint. A service reports UP if it is available and reports DOWN if it is unavailable. MicroProfile Health reports an individual service status at the endpoint and indicates the overall status as UP if all the services are UP. A service orchestrator can then use the health statuses to make decisions.

A service checks its own health by performing necessary self-checks and then reports its overall status by implementing the API provided by MicroProfile Health. A self-check can be a check on anything that the service needs, such as a dependency, a successful connection to an endpoint, a system property, a database connection, or the availability of required resources. MicroProfile offers checks for both liveness and readiness.

In the mpHealth-3.0 feature for Open Liberty:

The overall default Readiness status was changed to DOWN, with an empty response until all the deployed application(s) have been started. A new MicroProfile Config property (mp.health.default.readiness.empty.response=UP) is introduced to change the overall default Readiness check status to UP, during application start up, that do not have any user-defined health checks.

The HealthCheckResponseBuilder.state(Boolean UP) method was also renamed to HealthCheckResponseBuilder.status(Boolean UP) for HealthCheckResponse deserialization compatibility, where the JSON health check response string can now be deserialized into an HealthCheckResponse object.

The deprecated @Health qualifier was removed, and users should use the @Liveness or @Readiness qualifiers in their HealthCheck implementations, as appropriate.

Applications are expected to provide health check procedures by implementing the HealthCheck interface with the @Liveness or @readiness annotations. These are used by Open Liberty to verify the Liveness or Readiness of the application, respectively. Add the logic of your health check in the call() method, and return the HealthCheckResponse object, by using the simple up()/down() methods from the API:

[source, java]
----
**Liveness Check**
@Liveness
@ApplicationScoped
public class AppLiveCheck implements HealthCheck {
...
    @Override
     public HealthCheckResponse call() {
       ...
       HealthCheckResponse.up("my-liveness-check");
       ...
     }
}

**Readiness Check**
@Readiness
@ApplicationScoped
public class AppReadyCheck implements HealthCheck {
...
    @Override
     public HealthCheckResponse call() {
       ...
       HealthCheckResponse.named("my-app-readiness").status(isMyAppReady()).build();
       ...
     }
}
...
----

To view the status of each health check, access the either the `http://<hostname>:<port>/health/live` or `http://<hostname>:<port>/health/ready endpoints`.

More information: 
* link:https://github.com/eclipse/microprofile-health/releases/tag/3.0-RC3[MicroProfile Health Check 3.0 Release Page]
* link:https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/release_notes.asciidoc[Release notes]

[#opentracing]
=== MicroProfile OpenTracing 2.0

MicroProfile OpenTracing 2.0 can be used to profile and monitor applications built using microservice architecture.

MicroProfile OpenTracing 2.0 has upgraded the OpenTracing API to version 0.33.0.  This allows the 
use of tracing backends and their libraries that are built on OpenTracing API 0.33.0.

==== Try it now

Include the following in the server.xml:

[source, xml]
----
    <feature>mpOpenTracing-2.0</feature>
----

Also configure a tracing backend such as Jaeger or Zipkin 
    For Jaeger, add the following maven dependencies in the application's pom.xml.

[source, xml]
----
<dependency>
    <groupId>io.jaegertracing</groupId>
    <artifactId>jaeger-client</artifactId>
    <version>1.2.0</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.30</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-jdk14</artifactId>
    <version>1.7.30</version>
</dependency>
----

You can find out more about about Jaeger settings set up using environment variables by looking 
at link:https://github.com/jaegertracing/jaeger-client-java/blob/v1.2.0/jaeger-core/README.md[jaeger-client-java readme].

For the `JAEGER_PASSWORD` environment variable, the password can be encoded using the securityUtility command.

Depending on Jaeger’s sampling settings `JAEGER_SAMPLER_TYPE` and `JAEGER_SAMPLER_PARAM`, 
Jaeger may not report every spans created by the applications.

For Zipkin, link:https://github.com/WASdev/sample.opentracing.zipkintracer[see here].

Define your application in the server.xml:
[source, xml]
----
<webApplication location="yourapp.war" contextRoot="/yourapp">
    <!-- enable visibility to third party APIs -->
    <classloader apiTypeVisibility="+third-party" />
</webApplication>
----

Once you have hit some JAX-RS endpoints of your application, you should be able to find spans in the user interface of your tracing backend.

More information:

* link:https://github.com/eclipse/microprofile-opentracing[MicroProfile OpenTracting 2.0]

[#jakarta]
== Jakarta EE 9 Beta Features package

The main change visible to developers in the Jakarta EE 9 planned release is the names of packages changing to accomodate the new `jakarta.*` namespace. In this Open Liberty beta, we have more Jakarta EE 9 features with their name change completed. We've also made excellent TCK progress with these features.

This Open Liberty beta introduces the following Jakarta EE 9 features which now possess their all-new Jakarta EE 9 package names:

* jaspic-2.0
* jacc-2.0
* jpa-3.0 (The jpa-3.0 feature includes Eclipselink 3.0-RC1.)

These join the Jakarta EE 9 features in link:https://openliberty.io/blog/?search=beta&key=tag[previous Open Liberty betas]:

* Jakarta XML Binding 3.0 (`jaxb-3.0`)
* Jakarta Managed Bean 2.0 (`managedBeans-2.0`)
* Concurrency 2.0 (`concurrent-2.0`)
* Jakarta Enterprise Beans Home 4.0 (`ejbHome-4.0`)
* Jakarta Enterprise Beans Lite 4.0 (`ejbLite-4.0`)
* Bean Validation 3.0 (`beanValidation-3.0`)
* CDI 2.0 (`cdi-2.0`)
* WebSocket 2.0 (`websocket-2.0`; currently the integration with CDI is not completed)
* JPA 3.0 (`jpa-3.0`)
* JDBC 4.2 & 4.3 (`jdbc-4.2` & `jdbc-4.3`)
* JTA 2.0 (`transaction-2.0`)
* JSON-B 2.0 (`jsonb-2.0`)
* JSON-P 2.0 (`jsonp-2.0`)
* Servlet 5.0 (`servlet-5.0`)
* JSP 3.0 (`jsp-3.0`)
* Expression Language 4.0 (`el-4.0`)

==== Try it now

To try out these Jakarta EE 9 features on Open Liberty in a lightweight package, just update your build tools to pull the Open Liberty Jakarta EE 9 Beta Features package instead of the main release. The beta works with Java SE 14, Java SE 11, or Java SE 8.

If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty.beta</groupId>
    <artifactId>openliberty-jakartaee9</artifactId>
    <version>20.0.0.RELEASE_VERSION-beta</version>
    <type>zip</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty.beta', name: 'openliberty-jakartaee9', version: '[20.0.0.10-beta,)'
}
----

Or take a look at our link:{url-prefix}/downloads/#runtime_betas[Downloads page].

Enable the Jakarta EE 9 beta features in your app's `server.xml`. You can enable the individual features you want (but remember if you enable the `jsp-3.0` feature, the `servlet-5.0` and `el-4.0` features are automatically enabled for you) or you can just add the Jakarta EE 9 convenience feature to enable all of the Jakarta EE 9 beta features at once:

[source, xml]
----
  <featureManager>
    <feature>jakartaee-9.0</feature>
  </featureManager>
----

Or you can add the Web Profile convenience feature to enable all of the Jakarta EE 9 Web Profile beta features at once:

[source, xml]
----
  <featureManager>
    <feature>webProfile-9.0</feature>
  </featureManager>
----

=== HEADING

// // // // // // // //
// Remove if nothing else to say, or provide an update on aspect of the Jakarta EE 9 beta e.g- TCK
// // // // // // // //


[#feedback]
== Your feedback is welcomed

Let us know what you think on link:https://groups.io/g/openliberty[our mailing list]. If you hit a problem, link:https://stackoverflow.com/questions/tagged/open-liberty[post a question on StackOverflow]. If you hit a bug, link:https://github.com/OpenLiberty/open-liberty/issues[please raise an issue].


