---
layout: post
title: "Deploying an Open Liberty application to OpenShift with FIPS enabled"
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/28316667
author_github: https://github.com/mtamboli
seo-title: Deploying an Open Liberty application to OpenShift with FIPS enabled - OpenLiberty.io
seo-description: This post demonstrates how to run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled and deploy it to an OpenShift cluster.
blog_description: "This post demonstrates how to run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled and deploy it to an OpenShift cluster."
---
= Deploying an Open Liberty application to OpenShift with FIPS enabled
Monica Tamboli <https://github.com/mtamboli>

In this post, I'll show you how to run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled and deploy it to an OpenShift cluster.
First, let's cover some key concepts about FIPS and running Open Liberty with FIPS enabled.

== What is FIPS and why is it important?

Federal Information Processing Standards (FIPS) are standards and guidelines that are issued by the National Institute of Standards and Technology (NIST) for federal government computer systems. With digital revolution, Federal agencies and other industries rely on cryptography to protect digital information (data at rest) and communications (data in motion) to protect crtitcal information. FIPS specifies the security requirements a cryptographic module must satisfy to protect sensitive information. FIPS certification process requires testing by NIST accredited lab and assures users that a specific technology can be used to secure sensitive information.

United States government agencies and many other healthcare and financial firms use only products that support FIPS.
These standards ensure that the products conform to specified security requirements.
So, when you deploy an Open Liberty application to a Kubernetes cluster like OpenShift, it can be important to make sure that FIPS is enabled.

== Considerations for enabling FIPS

=== Kubernetes cluster considerations

First, you need to decide whether to install your Kubernetes cluster in FIPS mode.
In this blog, we'll use OpenShift 4.6. Starting in version 4.3, you can https://docs.openshift.com/container-platform/4.6/installing/installing-fips.html[install an OpenShift cluster that uses FIPS Validated / Modules in Process cryptographic libraries].

=== Open Liberty considerations
Open Liberty can run with any compliant Java runtime environment (JRE) or Java software development kit (SDK). When enabling FIPS, it is necessary to make sure that the underlying java libraries are FIPS validated. In this blog, we will use Open Liberty  with https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/enablefips.html[IBM JDK 8 using IBMJSSE2 FIPS]. No changes to the application to support IBMJSSE2 running in FIPS mode are required.
Open Liberty can support FIPS 140-2, https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_nist.html[SP800-131, and Suite B security standards].
Your application could stop working after enabling FIPS if the other software that your application interacts with isn't FIPS-compliant.
However, a FIPS-enabled Open Liberty image can be installed on a Kubernetes cluster that isn't FIPS-enabled.

Let's explore the steps to enable FIPS for an Open Liberty application that's running on a FIPS-enabled OpenShift cluster:

* <<create-image-fips,Creating an Open Liberty application container image that has FIPS enabled>>
* <<deploy-image-cluster,Deploying the Open Liberty image to your OpenShift cluster>>

[#create-image-fips]
== Creating an Open Liberty application container image that has FIPS enabled

. https://github.com/OpenLiberty/ci.docker#container-images[Create an Open Liberty application container image]. To enable FIPS for Open Liberty, we will use the Open Liberty image that uses JDK 8.

. Ensure that TLS is enabled for your Open Liberty server by adding the xref:/docs/latest/reference/feature/transportSecurity-1.0.html[Transport Security feature] (`transportSecurity-1.0`) to your `server.xml` file.

. Set the correct system property to https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/enablefips.html[enable FIPS mode in the IBMJSSE2 provider].
.
For FIPS140-2, set the `-Dcom.ibm.jsse2.usefipsprovider=true` property.
SP800-131a can also be enabled by using the `-Dcom.ibm.jsse2.sp800-131=transition` property or the `-Dcom.ibm.jsse2.sp800-131=strict` property.
To set this system property, create or update the `jvm.options` file, as shown in the following example:
+
----
$ cat jvm.options
-Dcom.ibm.jsse2.usefipsprovider=true
----
+

. Add the Java Cryptography Extension (JCE) FIPS provider in the `java.security` file, which is located in the `JAVA_HOME/jre/lib/security` directory. By default, the `java.security` file doesn't include a FIPS provider. This examples uses `com.ibm.crypto.fips.provider.IBMJCEFIPS` FIPS provider although later versions of also support `com.ibm.crypto.plus.provider.IBMJCEPlusFIPS` as dcoumented https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/enablefips.html[here].

.. You can extract the `java.security` file from the Open Liberty running pod:
+
----
$ docker cp <container>:/opt/ibm/java/jre/lib/security/java.security .
----
.. Add the FIPS provider and adjust the provider number in the `java.security` file:
+
----
$ vi java.security
# List of providers and their preference orders (see above):
#Added the security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS on top
security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS
security.provider.2=com.ibm.jsse2.IBMJSSEProvider2
security.provider.3=com.ibm.crypto.provider.IBMJCE
.....
----

. Update the Dockerfile with updated `server.xml`, `jvm.options`, and `java.security` files, as shown in the following example Dockerfile:
+
----
FROM openliberty/open-liberty:21.0.0.1-full-java8-ibmjava-ubi

COPY --chown=1001:0  server.xml /config/
COPY --chown=1001:0  jvm.options /config/
COPY --chown=1001:0 <app> /config/apps
COPY --chown=1001:0 java.security /opt/ibm/java/jre/lib/security
RUN configure.sh
----
. Run the following command to build the updated Open Liberty image:
+
----
$ docker build -t <image_name> -f Dockerfile .
----
. You can optionally verify application container image created above to make sure that the correct JSSE provider is being used by enabling JSSE trace using `-Djavax.net.debug=all` property. 
+
----
 $ docker run -e JVM_ARGS=-Djavax.net.debug=all -p 9443:443 <image_name>

...
********************************************************************************
product = Open Liberty 21.0.0.1 (wlp-1.0.48.cl210120210113-1459)
...
[2/16/21 17:02:19:243 UTC] 0000002a SystemOut                                                    O IBMJSSE2 will use default F
IPS provider IBMJCEFIPS
[2/16/21 17:02:19:244 UTC] 0000002a SystemOut                                                    O Installed Providers =
[2/16/21 17:02:19:244 UTC] 0000002a SystemOut                                                    O      IBMJCEFIPS
[2/16/21 17:02:19:245 UTC] 0000002a SystemOut                                                    O      IBMJSSE2
[2/16/21 17:02:19:245 UTC] 0000002a SystemOut                                                    O      IBMJCE
...
----
. Log in to your image registry and push the image.
In this example, we use the OpenShift internal registry:
+
----
$ docker login <registry>
$ docker tag <image_name> default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
$ docker push default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
----

[#deploy-image-cluster]
== Deploying the Open Liberty image to your OpenShift Cluster

. Deploy an OpenShift cluster.

. Install the https://github.com/OpenLiberty/open-liberty-operator#operator-installation[Open Liberty Operator].

. Log in to your OpenShift cluster by using the `oc login` command.

. Create a project for your Open Liberty application by running the following command:
+
----
$ oc new-project ol-app
----
. Create an https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc[OpenLibertyApplication custom resource (CR)] to deploy your application.
It's important that route for the application is enabled so that TLS can use FIPS.
The following example file shows how you might configure the Open Liberty Operator for deployment to an OpenShift cluster.
Make sure to replace `<image_name>` with the name of your image:
+
----
$ cat app-deploy.yaml
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: inventory-ibmjdk
spec:
  replicas: 1
  applicationImage: default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
  expose: true
  route:
    termination: reencrypt
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: inventory-ibmjdk-svc-tls
    certificateSecretRef: inventory-ibmjdk-svc-tls
    port: 9443
----


. Deploy the application to OpenShift by running the following command:
+
----
$ oc apply -f app-deploy.yaml
----

. Check the pod and route of your application:
+
----
$ oc get pods
inventory-ibmjdk-687487479-4rxk7   1/1     Running   0          36h
$ oc get routes|grep jdk
inventory-ibmjdk   inventory-ibmjdk-ol-app.apps.example.ibm.com          inventory-ibmjdk   9443-tcp   reencrypt     None
----

. Open a browser and access the route that was returned in the previous step, for example, https://inventory-ibmjdk-ol-app.apps.example.ibm.com.

== Summary

Security is obviously a top priority for any organization.
Different levels of FIPS can be enabled for Open Liberty applications when you use the IBM JDK 8.
It's important to take into consideration all of the dependencies of an application before you enable FIPS to make sure that the application will continue to work when it's FIPS-compliant.
If you're already using Open Liberty applications with FIPS enabled on-premises, you can move to Kubernetes by making sure that you pick the Open Liberty image with IBM JDK 8 and update the container image with FIPS-enabled files.
