---
layout: post
title: "Running Open Liberty in a FIPS-enabled cluster"
categories: blog
author_picture: https://avatars3.githubusercontent.com/u/28316667
author_github: https://github.com/mtamboli
seo-title: Running Open Liberty in a FIPS-enabled cluster - OpenLiberty.io
seo-description: This post demonstrates how to run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled.
blog_description: "This post demonstrates how to run an Open Liberty application with Federal Information Processing Standards (FIPS) enabled."
---
= Running Open Liberty in a FIPS-enabled cluster
Monica Tamboli <https://github.com/mtamboli>

**What is FIPS?**

Federal Information Processing Standards (FIPS) are standards and guidelines issued by the National Institute of Standards and Technology (NIST) for federal government computer systems.  FIPS specifies required levels of encryption for Transport Layer Security/Secure Sockets Layer (TLS/SSL). This standard ensures high protection of data as it is sent over the wire.

**Why Should I care?**

US government agencies and many other healthcare and financial firm use only products which support FIPS. These standards to ensure that the products conform to specified security requirements. So when deploying Liberty application to a Kubernetes cluster like OpenShift, it will be important for some organization to enable FIPS. 

**Considerations for Kubernetes cluster:**

First decision is whether to install your kubernetes cluster in FIPS mode. Starting with version 4.3, you can install an https://docs.openshift.com/container-platform/4.6/installing/installing-fips.html[OpenShift Container Platform cluster that uses FIPS Validated / Modules in Process cryptographic libraries].

**Consideration for enabling FIPS for your application runtime Liberty:**

Liberty support FIPS by using using IBMJSSE2 FIPS provider in IBM JDK 8. Liberty server can support FIPS 140-2, SP800-131 and Suite B security standards. At this time, IBM JDK 8 has to be used for the FIPS compliance with Liberty. More JDKs should support FIPS in future. Your application may stop working aftr enabling FIPS if all other softwares with which your application interacts are not FIPS compliant like LDAP and Database etc. FIPS enabled Liberty image can be installed on a cluster whether it is FIPS enabled or not.

Let us explore steps to enable FIPS for a Liberty application running on FIPS enabled OpenShift Cluster. These steps should apply if Liberty application on any other Kubernetes cluster as well. 

. <<create-image-fips,Creating an Open Liberty Docker image that has FIPS enabled>>
. <<deploy-image-cluster,Deploying the Open Liberty image to your OpenShift Cluster>>
. <<verify-fips,Verifying that FIPS is enabled on the Open Liberty server>>


[#create-image-fips]
== Creating an Open Liberty Docker image that has FIPS enabled

. https://github.com/OpenLiberty/ci.docker#container-images[Create an Open Liberty Docker image]. To enable FIPS for Open Liberty, use the Open Liberty image that uses the IBM JDK.

. Ensure that SSL is enabled for your Open Liberty server by adding the feature:transportSecurity[display=Transport Security feature] (`transportSecurity-1.0`) to your `server.xml` file.

. Set the `com.ibm.jsse2.usefipsprovider` system property to  https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/enablefips.html[enable FIPS mode in the `IBMJSSE2` provider].
  * To set this property, create or update the `jvm.options` file in the server configuration directory, as shown in the following example:
+
----
$ cat jvm.options
-Dcom.ibm.jsse2.usefipsprovider=true
----
*  Optional in development environment: If you need to enable JSSE trace for debugging or verification purposes `-Djavax.net.debug=all` property can be added to the jvm.options. By default, trace gets written to messages.log file.


. Add `com.ibm.crypto.fips.provider.IBMJCEFIPS` Java Cryptography Extension (JCE) FIPS provider on top in the `java.security` file, which is located in the `JAVA_HOME/jre/lib/security` directory. By default java.security file does not have FIPS provider in the list.
  * `java.security` file can be extracted from from the liberty image or from a running pod as follows
+
----
$ docker run -v $PWD:/opt/mount --rm -ti openliberty/open-liberty:21.0.0.1-full-java8-ibmjava-ubi bash -c "cp /opt/ibm/java/jre/lib/security/java.security /opt/mount/"
or
$ oc rsync <pod-name>:/opt/ibm/java/jre/lib/security/java.security .
----
+
  * Update 'java.security` file to add the correct FIPS provider and adjust the provider number. 
+
----
$ vi java.security
# List of providers and their preference orders (see above):
#Added the security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS on top
security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS
security.provider.2=com.ibm.jsse2.IBMJSSEProvider2
security.provider.3=com.ibm.crypto.provider.IBMJCE
.....
----

. Update Dockerfile with updated `server.xml`, `jvm.options`, and `java.security` files, as shown in the following example `Dockerfile.ibmjdk` file. https://github.com/OpenLiberty/ci.docker[Follow this link for details on creating Open Liberty images] :
+
----
FROM openliberty/open-liberty:21.0.0.1-full-java8-ibmjava-ubi

COPY --chown=1001:0  server.xml /config/
COPY --chown=1001:0  jvm.options /config/
COPY --chown=1001:0 <app> /config/apps
COPY --chown=1001:0 java.security /opt/ibm/java/jre/lib/security
RUN configure.sh
----
. Run the following command to build the updated Open Liberty image:
+
----
$ docker build -t <image_name> -f Dockerfile.ibmjdk .
----

. Log in to your image registry and push the image.
In this example, we use the OCP internal registry:
+
----
$ docker login <registry>
$ docker tag <image_name> default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
$ docker push default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
----

[#deploy-image-cluster]
== Deploying the Open Liberty image to your OpenShift Cluster

. Deploy an OpenShift Container Platform (OCP) cluster. If you want to run Open Liberty on a FIPS-enabled OCP cluster, see the https://docs.openshift.com/container-platform/4.6/installing/installing-fips.html[OpenShift documentation].
. Install the xref:open-liberty-operator.adoc[Open Liberty Operator].
. Login to your OCP cluster by using the `oc login` command.

. Create a project for your Open Liberty application by running the following command:
+
----
$ oc new-project ol-app
----
. Create Open Liberty Application CR to deploy your application. https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc[See Open Liberty Operator user guide for details.] 
It's important that route for the application is enabled so that SSL can use FIPS. The following example file shows how you might configure the Open Liberty Operator for deployment to an OCP cluster.  :

----
$ cat app-deploy_ssl.yaml
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: inventory-ibmjdk
spec:
  replicas: 1
  applicationImage: default-route-openshift-image-registry.apps.example.ibm.com/ol-app/<image_name>
  expose: true
  route:
    termination: reencrypt
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: inventory-ibmjdk-svc-tls
    certificateSecretRef: inventory-ibmjdk-svc-tls
    port: 9443
----


. Replace the <image_name> in above example app-deploy_ssl.yaml file. Deploy the application to OCP by running the following command:
+
----
$ oc apply -f app-deploy_ssl.yaml
----

. Check the pod and route of your application:
+
----
$ oc get pods
inventory-ibmjdk-687487479-4rxk7   1/1     Running   0          36h
$ oc get routes|grep jdk
inventory-ibmjdk   inventory-ibmjdk-ol-app.apps.example.ibm.com          inventory-ibmjdk   9443-tcp   reencrypt     None
----

. Open a browser and access the route that was returned in the previous step, for example, https://inventory-ibmjdk-ol-app.apps.example.ibm.com.

[#verify-fips]
== Optional in development environment: Verifying that FIPS is enabled on the Open Liberty server

. Enable JSSE trace (if not enabled in earlier step) by updating the `jvm.options` file to add the following property and rebuild the Open Liberty image and redeploy the new image to OCP:
+
----
-Djavax.net.debug=all
----

. Access the Open Liberty application at the same route that you accessed in the previous section, for example, https://inventory-ibmjdk-ol-app.apps.example.ibm.com.

. Check the logs on the Open Liberty container, as shown in the following example:
+
----
$oc rsh inventory-ibmjdk-687487479-4rxk7 bash
bash-4.4$ more /logs/messages.log
...
********************************************************************************
product = Open Liberty 21.0.0.1 (wlp-1.0.48.cl210120210113-1459)
...
[2/16/21 17:02:19:243 UTC] 0000002a SystemOut                                                    O IBMJSSE2 will use default F
IPS provider IBMJCEFIPS
[2/16/21 17:02:19:244 UTC] 0000002a SystemOut                                                    O Installed Providers =
[2/16/21 17:02:19:244 UTC] 0000002a SystemOut                                                    O      IBMJCEFIPS
[2/16/21 17:02:19:245 UTC] 0000002a SystemOut                                                    O      IBMJSSE2
[2/16/21 17:02:19:245 UTC] 0000002a SystemOut                                                    O      IBMJCE
...
$  grep ClientHello /logs/messages.log
[2/16/21 17:05:00:861 UTC] 0000003d SystemOut                                                    O *** ClientHello, TLSv1.2
----
