---
layout: post
title: "Open source, cloud-native Java at DevNexus 2023!"
# Do NOT change the categories section
categories: blog
author_picture: https://avatars3.githubusercontent.com/GraceJansen
author_github: https://github.com/GraceJansen
seo-title: Open source, cloud-native Java at DevNexus 2023 - OpenLiberty.io
seo-description: A summary of some of the MicroProfile, Jakarta EE and Open Liberty activities at DevNexus 2023.
blog_description: A summary of some of the MicroProfile, Jakarta EE and Open Liberty activities at DevNexus 2023.
---
= Open source cloud-native Java at DevNexus 2023!
Grace Jansen <https://github.com/GraceJansen>

//Blank line here is necessary before starting the body of the post.

== What is DevNexus?
link:https://devnexus.com/[DevNexus] is the longest-running and largest Java Conference in the USA. It’s organised by a vibrant Java community and is being held in Atlanta this year from April 4-6. After the COVID-19 pandemic and its long-lasting effects, it’s wonderful to be able to come together again and have such a fantastic opportunity to re-connect with the wider Java community! And of course, we can’t wait to join too! 

There will be several members of the Open Liberty team on-site hosting sessions, quick labs, workshops, and running demonstrations at the IBM booth. If you’re going to be there, deciding which of the great sessions to see can be challenging. To help you decide, we’ve put together a useful summary of the sessions on MicroProfile, Jakarta EE, and Open Liberty.


== Tuesday April 4th:

Workshop: link:https://devnexus.com/presentations/thriving-in-the-cloud-venturing-beyond-the-12-factors/[Thriving in the cloud: Venturing beyond the 12 factors]

In this workshop, you’ll get hands on with some of the most innovative and exciting open source cloud-native Java technologies, including Open Liberty, MicroProfile, Jakarta EE, TestContainers, OpenJ9, and more! Emily Jiang, Rich Hagarty, Cindy High, and Harry Hoots will show you how to venture beyond the 12 factors to design and develop applications with the 15-factor app methodology. Don’t miss your chance to join this fantastic interactive learning opportunity!


== Wednesday April 5th:

Talk: link:https://devnexus.com/presentations/jakarta-ee-for-spring-developers[Jakarta EE for Spring Developers]

Jakarta EE guru Ivar Grimstad teaches us how to transition our package namespace from `javax.\*` to `jakarta.*` and why it matters to everyone in the Java ecosystem. A live coding demo will take us through the steps involved, and point out where to pay special attention.


Talk: link:https://devnexus.com/presentations/enhancing-java-applications-for-the-cloud/[Enhancing Java applications for the cloud]

In this talk, Tobi Ajila, a Java Runtime developer for the Eclipse OpenJ9 team in Canada, will showcase how technologies like checkpoint/restore and remote JIT compilation can help boost startup time and reduce memory footprint to minimize your application’s costs. Attendees will learn how these features integrate seamlessly with existing container technologies for simple, secure, and predictable deployments. Whether you are a cloud veteran or a newcomer, there will be lots to learn!


Deep Dive Session: link:https://devnexus.com/presentations/deep-dive-microprofile-6-0-with-jakarta-ee-10-core-profile[Deep Dive MicroProfile 6.0 with Jakarta EE 10 Core Profile]

Java champion Emily Jiang leads this deep dive session all around the exciting new updates from MicroProfile 6.0 and Jakarta EE 10. Included in this talk are some of the major updates within MicroProfile Metrics, which enables the adoption of Micrometer, and MicroProfile Telemetry, which consumes OpenTelemetry. Join this session to learn all about the observability standards for your microservices with a live demo on Open Liberty.


== Thursday April 6th:

Talk: link:https://devnexus.com/presentations/jakarta-ee-10-and-beyond[Jakarta EE 10 and Beyond]

In this session, Reza Rahman (Principal Program Manager for Java on Azure at Microsoft) offers a brief tour of Jakarta EE 10 as well as a look at what the future might bring. If you’re up for a session that’s both useful and exploratory, then make sure you check out this session! As Reza says: “You should come to this session with your thinking caps on and your sleeves rolled up. There is much to help move forward together that really matters.”


Talk: link:https://devnexus.com/presentations/journey-to-cloud-leave-no-java-workload-behind[Journey to cloud : leave no Java workload behind]

In this talk, IBMers Vijay Sundaresan and Mark Stoodley take on the daunting task of pulling together the full landscape of the exiting new technologies that can enable key cloud-native behaviours and characteristics, including fast startup times and low memory footprints. They’ll explain how many of these technologies and enhancements were developed at OpenJ9 and how they all fit together as a compelling and cooperative solution to optimize Java for the cloud.
Interested? Then join what is sure to be an interesting session!


Panel Session: link:https://devnexus.com/presentations/5-years-of-jakarta-ee-panel-a-look-into-the-future[5 years of Jakarta EE Panel: a look into the future]

If you’re interested in a more interactive session, then be sure to bookmark this panel session! Jakarta EE experts (Ivar Grimstad, Tanja Obradovic, Emily Jiang, Jose Paumard, Mark Heckler, and Rudy De Busscher) will form the panel for this session, discussing the future of Jakarta EE with version 11 and beyond. Pop along to this session to ask those burning questions and gain exciting insight into where this fantastic open source technology is heading.


Talk: link:https://devnexus.com/presentations/jakarta-ee-integration-testing[Jakarta EE integration testing]

In this session, Rudy De Busscher explores scenarios of how you can use the Testcontainers framework to test your Jakarta EE application, including a remote debug session of your code.


Talk: link:https://devnexus.com/presentations/best-practices-for-securing-cloud-native-applications[Best Practices for Securing Cloud Native Applications]

In this talk, chief architect for IBM Java Mark Stoodley will cover some best practices for authenticating users and authorizing them to access your microservice. He’ll provide an overview of microservice security, with samples based on the Open Liberty runtime. With the ever-growing importance of effectively securing our applications, this is sure to be a great session to attend.

== IBM Booth:

As well as the numerous sessions during the conference, the Open Liberty team will also be manning the IBM booth in the exhibition hall. Stop by to get hands on with our quick labs (featuring InstantOn startup of cloud-native Java apps, MicroProfile and Jakarta EE), grab some awesome swag, and have a chat about all things OSS Java. We’d love to see you there!

This year, we’ll also have our exiting intergalactic booth challenge…
link:https://www.youtube.com/watch?v=bURqsxP5gEY&t=139s[The Open Liberty Space Rover Challenge]. In this challenge, you’ll need to navigate the planets and get your rover safely to your destination in the stars. Take control of a spaceship and use hand signals to direct it's flight from planet to planet. Climb the rankings on your way to become top cadet in Star Academy. Our Space Rover Challenge leverages a variety of technologies, including hardware and modern Java technology. While you're with us, ask our developers about the underlying technologies they've used to create the demo, including Open Liberty, also known as "the most flexible runtime in the cosmos", Jakarta EE, MicroProfile, and OpenJ9.

video::bURqsxP5gEY[youtube, width="560", height="315", align="center"]

Check out link:https://developer.ibm.com/events/devnexus-2023-atlanta/?mhsrc=ibmsearch_a&mhq=devnexus[IBM’s presence] at DevNexus as well as the link:https://devnexus.com/schedule[full schedule] on the link:https://devnexus.com/[conference website].
