---
layout: post
title: "TITLE"
categories: blog
author_picture: https://avatars3.githubusercontent.com/
author_github: https://github.com/GITHUB_USERNAME
seo-title: TITLE - makes sure it ends with - OpenLiberty.io
seo-description: DESCRIPTION
blog_description: DESCRIPTION
---
= TITLE
AUTHOR_NAME <https://github.com/GITHUB_USERNAME>
:imagesdir: /
:url-prefix:
:url-about: /about/
// tag::intro[]
RELEASE_SUMMARY
In link:{url-about}[Open Liberty] 20.0.0.9:
* <<TAG_1, FEATURE_1_HEADING>>
* <<TAG_2, FEATURE_2_HEADING>>
** <<SUB_TAG_1, SUB_FEATURE_1_HEADING>>
** <<SUB_TAG_2, SUB_FEATURE_2_HEADING>>
* <<TAG_3, FEATURE_3_HEADING>>
View the list of fixed bugs in link:https://github.com/OpenLiberty/open-liberty/issues?q=label%3Arelease%3A20009+label%3A%22release+bug%22+[20.0.0.9].
// end::intro[]
// tag::run[]
[#run]

== Run your apps using 20.0.0.9
If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:
[source,xml]
----
<dependency>
    <groupId>io.openliberty</groupId>
    <artifactId>openliberty-runtime</artifactId>
    <version>20.0.0.9</version>
    <type>zip</type>
</dependency>
----
Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:
[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty', name: 'openliberty-runtime', version: '[20.0.0.9,)'
}
----
Or if you're using Docker:
[source]
----
FROM open-liberty
----
//end::run[]
Or take a look at our link:{url-prefix}/downloads/[Downloads page].
[link=https://stackoverflow.com/tags/open-liberty]
image::img/blog/blog_btn_stack.svg[Ask a question on Stack Overflow, align="center"]
//tag::features[]
[#acme]
=== Install a signed certifacte with ACME Certificate Authority (acmeCA-2.0)

For default Transport Security (SSL/TLS) support, Open Liberty provides a self-signed certificate. With the ACME feature, a Certificate Authority signed certificate can be installed, providing a trusted certificate for an improved testing or user experience.The self signed certificate from Open Liberty allows you to enable transport security right away, but the certificate is marked as insecure and users have to accept the warnings when accessing a website with a self signed certificate. A signed certificate can be costly and may not be available during testing. Getting a Certificate Authority signed certificate (for example, Lets Encrypt), provides a middle ground of a trusted certificate.
To use the ACME feature, you need to provide the directory URI for the ACME Certificate Authority (CA) and the domain name for the server. Public ACME providers call back on port 80 to verify domain ownership before issuing a certificate. When the Open Liberty server starts, the provided CA directory URI will be used to request a certificate. The CA signed certificate is installed in the keystore and acts as the default certificate.
Add the feature to the `server.xml`:
[source, xml]
----
<featureManager> 
    <feature>acmeCA-2.0</feature>
</featureManager>
<acmeCA directoryURI="https://acme.host.com/directory" >
    <domain>theDomainThatIOwn.com</domain>
   <accountContact>mailto:my_email_addr@theDomainThatIOwn.com</accountContact>
</acmeCA>
<httpEndpoint host="*" httpPort="80" httpsPort="443" id="defaultHttpEndpoint"/>
<keyStore password="password_for_keystore" id="defaultKeyStore"/>
----
For more information:
* https://en.wikipedia.org/wiki/[High level summary of the ACME protocol]
* https://tools.ietf.org/html/rfc8555[The ACME spec]
* https://letsencrypt.org/[Popular public ACME CA]
[#TAG_2]
== FEATURE_2_TITLE

[#SUB_TAG_1]
=== SUB_FEATURE_1_TITLE

Add the feature to the `server.xml`:
[source, xml]
----
<server>
  <featureManager>
    <feature>FEATURE</feature>
  </featureManager>
</server>
----
[#SUB_TAG_2]
=== SUB_FEATURE_2_TITLE

Add the feature to the `server.xml`:
[source, xml]
----
<server>
  <featureManager>
    <feature>FEATURE</feature>
  </featureManager>
</server>
----
[#TAG_3]
== FEATURE_3_TITLE

For more details, check the LINK[LINK_DESCRIPTION].
//end::features[]
== Get Open Liberty 20.0.0.9 now
Available through <<run,Maven, Gradle, Docker, and as a downloadable archive>>.