---
layout: post
title: "TITLE"
categories: blog
author_picture: https://avatars3.githubusercontent.com/jakub-pomykala
author_github: https://github.com/jakub-pomykala
seo-title: TITLE - makes sure it ends with - OpenLiberty.io
seo-description: DESCRIPTION
blog_description: DESCRIPTION
---
= TITLE
AUTHOR_NAME <https://github.com/GITHUB_USERNAME>
:imagesdir: /
:url-prefix:
:url-about: /about/
// // // // // // // //
// Above:
// Do not insert any blank lines between any of the lines above.
// Do not remove or edit the variables on the lines beneath the author name.
//
// Replace TITLE with the blog post title eg: MicroProfile 3.3 is now available on Open Liberty 20.0.0.4
// Replace GITHUB_USERNAME with your GitHub username eg: lauracowen
// Replace DESCRIPTION with a short summary (~60 words) of the release (a more succinct version of the first paragraph of the post).
// Replace AUTHOR_NAME with your name as you'd like it to be displayed, eg: Laura Cowen
// // // // // // // //

BETA_RELEASE_SUMMARY

// // // // // // // //
// Change the RELEASE_SUMMARY to a quick sentence intro. Make sure to keep the blank lines 
// // // // // // // //
We have two beta packages for link:{url-about}[Open Liberty]:

* <<jakarta, Jakarta EE 9 Beta Features>>: a lightweight package that contains only the Jakarta EE 9 features.
* <<allbeta, All Beta Features>>: a new, larger package that contains all Open Liberty beta and GA features and functions.

This means that you can now try out our in-development Open Liberty features by just adding the relevant coordinates to your build tools (either the Jakarta EE 9 Beta Features package or the All Beta Features package, depending on what you want to try).

If you try either package, <<feedback, let us know what you think>>.
[#jakarta]
== Jakarta EE 9 Beta Features package

The main change visible to developers in the Jakarta EE 9 planned release is the names of packages changing to accomodate the new `jakarta.*` namespace. In this Open Liberty beta, we have more Jakarta EE 9 features with their name change completed. We've also made excellent TCK progress with these features.
// // // // // // // //
// ABOVE:
// Update the second and third sentence appropriately for this release
// // // // // // // //

This Open Liberty beta introduces the following Jakarta EE 9 features which now possess their all-new Jakarta EE 9 package names:

* ITEM_1
* ITEM_2
* ITEM_3
// // // // // // // //
// ABOVE:
// Change the ITEMS above to list the new changes and features in this
// beta release
// // // // // // // //


These join the Jakarta EE 9 features in link:https://openliberty.io/blog/?search=beta&key=tag[previous Open Liberty betas]:

// // // // // // // //
// Copy feature from both lists in the previous beta post creating    // a cumulative list from all previous betas to make a list of all    // existing features in the new beta.
// // // // // // // //

=== Try it now

To try out these Jakarta EE 9 features on Open Liberty in a lightweight package, just update your build tools to pull the Open Liberty Jakarta EE 9 Beta Features package instead of the main release. The beta works with Java SE 14, Java SE 11, or Java SE 8.

If you're using link:{url-prefix}/guides/maven-intro.html[Maven], here are the coordinates:

[source,xml]
----
<dependency>
    <groupId>io.openliberty.beta</groupId>
    <artifactId>openliberty-jakartaee9</artifactId>
    <version>20.0.0.RELEASE_VERSION-beta</version>
    <type>zip</type>
</dependency>
----

Or for link:{url-prefix}/guides/gradle-intro.html[Gradle]:

[source,gradle]
----
dependencies {
    libertyRuntime group: 'io.openliberty.beta', name: 'openliberty-jakartaee9', version: '[20.0.0.RELEASE_VERSION-beta,)'
}
----
// // // // // // // //
// Above:
// Replace RELEASE_VERSION with the version number of Open Liberty
// // // // // // // //
Or take a look at our link:{url-prefix}/downloads/#runtime_betas[Downloads page].

Enable the Jakarta EE 9 beta features in your app's `server.xml`. You can enable the individual features you want (but remember if you enable the `jsp-3.0` feature, the `servlet-5.0` and `el-4.0` features are automatically enabled for you) or you can just add the Jakarta EE 9 convenience feature to enable all of the Jakarta EE 9 beta features at once:

[source, xml]
----
  <featureManager>
    <feature>jakartaee-9.0</feature>
  </featureManager>
----

Or you can add the Web Profile convenience feature to enable all of the Jakarta EE 9 Web Profile beta features at once:

[source, xml]
----
  <featureManager>
    <feature>webProfile-9.0</feature>
  </featureManager>
----

=== HEADING

// // // // // // // //
// Remove if nothing else to say, or provide an update on aspect of the Jakarta EE 9 beta e.g- TCK
// // // // // // // //

[#allbeta]
== All Beta Features package

As well as the Jakarta EE 9 features listed above, the new All Beta Features package contains our new MicroProfile Fault Tolerance 3.0, MicroProfile Metrics 3.0, MicroProfile Health 3.0 and MicroProfile OpenTracing 2.0 features which have been available in our link:/downloads/#development_builds[nightly builds] for a few weeks but are now easy to install from Maven Central too.
// // // // // // // //
// Above:
// Change FEATURES to a feature that is included in this release     // version.
// // // // // // // //

[#fault3.0]
=== MicroProfile Fault Tolerance 3.0

MicroProfile Fault Tolerance allows developers to easily apply strategies for mitigating failure to their code. It provides annotations which developers can add to methods to use bulkhead, circuit breaker, retry, timeout and fallback strategies.

Fault Tolerance 3.0 overhauls the metrics automatically exported by Fault Tolerance to take advantage of metric tags to make it easier to use those metrics to understand when and where your application is failing.

Information which was previously included in the metric name is now included as metric tags, making it much easier to query for data from multiple methods and pick out which, if any, is causing issues.

Example:

Old metric: `application:ft.<name>.timeout.callsTimedOut.total`

New metric: `base:ft.timeout.calls.total{method="<name>", timedOut="true"}``


=== Try it now 

Enable Fault Tolerance 3.0 and CDI in the server.xml, along with any other features you're using.

[source, xml]
----
<featureManager>
  <feature>mpFaultTolerance-3.0</feature>
  <feature>cdi-2.0</feature>
  <feature>jaxrs-2.1</feature>
</featureManager>
----

Add any of the Fault Tolerance annotations to a business method of a CDI bean.

[source, java]
----
@Retry(5)
public User lookupUserFromRegistry(String name) {
  return registry.getUser(name);
}
----

When that method is called as a a CDI business method, the fault tolerance strategy will be used. In this example, if `lookupUserFromRegistry()` would throw an exception, it will instead be retried up to five times.

Get an introduction to MicroProfile Fault Tolerance with the Open Liberty guides:
* link:https://openliberty.io/guides/retry-timeout.html[Failing fast and recovering from errors]
* link:https://openliberty.io/guides/circuit-breaker.html[Preventing repeared failed calls to microservices]

References to:
* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/apidocs/[Java]
* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/microprofile-fault-tolerance-spec.html[Full Specification]
* link:https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0-RC2/microprofile-fault-tolerance-spec.html#_integration_with_microprofile_metrics[New format for metrics in detail in Chapter 11]

link:https://github.com/OpenLiberty/open-liberty/[Report any issues on Github]


[#metric3.0]
=== MicroProfile Metric 3.0

MicroProfile Metrics 3.0 (as part of MicroProfile 4.0) introduces new metric values for the existing SimpleTimer and Timer metrics. Additionally a new REST metric is introduced for better monitoring and handling of unmapped exceptions. Manual configuration for re-usability has been removed. A notable change to the MP Metrics programming model regarding CDI Producers has been made. Lastly a medley of API improvements and refactoring have been added in this release.

==== SimpleTimer
The SimpleTimer metric now tracks and reports the highest and lowest recorded time duration of the previous complete minute. See the SimpleTimer.java for more more information in the Javadoc.

==== Timer
The Time metric now tracks and reports the total elapsed time duration. See the Tiimer.java for more information in the Javadoc.

==== REST metric
A new REST.request.unmappedException.total metric that is backed by a counter metric has been introduced. Similar to the REST.request metric, there will be one unique metric for each REST endpoint identified by a class and method label. The new REST metric will count the amount of times the request ends in an unmapped exception. The REST.request metric corresponding to this REST endpoint will not record any values if an unmapped exception has occured.

==== CDI Producer
The @Metrics annotation will no longer support the method target (i.e it can not be annotated on a method). Additionally, it will not support usage with CDI Producers.

=== Try it now 

Enable Metrics 3.0 in the server.xml, along with any other features you're using.

[source, xml]
----
<featureManager>
    <feature>mpMetrics-3.0</feature>
</featureManager>
----

More information:

* link:https://github.com/eclipse/microprofile-metrics/releases/tag/3.0-RC1[MicroProfile Metrics 3.0 Release Page]
* link:https://github.com/eclipse/microprofile-metrics/blob/3.0-RC1/spec/src/main/asciidoc/changelog.adoc[Release Notes]

[#feedback]
== Your feedback is welcomed

Let us know what you think on link:https://groups.io/g/openliberty[our mailing list]. If you hit a problem, link:https://stackoverflow.com/questions/tagged/open-liberty[post a question on StackOverflow]. If you hit a bug, link:https://github.com/OpenLiberty/open-liberty/issues[please raise an issue].


